# Introduction


## Basic Information

This assessment reports the status of `r spp` (*`r spp_latin`*) off the `r state` coast using data through `r endyr`. 

The stock off the `r state` coast was assessed as a separate stock from other populations off the U.S. West Coast based on the fairly sedentary nature of `r spp` which likely limits flow of fish to California and Washington [@HannahandRankin_rockfish_site_fidelity_2011; @tolimieri_home_2009]. The substrate of the southern Washington coast is typically sandy bottom, which creates a natural separation between the Oregon and Washington populations. Additionally, the exploitation history and magnitude of removals off the `r state` coast differ from those in Washington and California.    


## Life History

`r Spp` are a medium- to large-sized nearshore rockfish found from southern California to the Gulf of Alaska [@loveetal_2002]. Off the U.S. West Coast `r spp` are primarily located north of central California, with rare observations south of Point Conception. 'r Spp' have historically been a part of both commercial and recreational fisheries throughout their range. 

`r Spp` are found in waters less than 274 meters in depth in nearshore kelp forests and rocky habitat [@loveetal_2002]. The diets of `r spp` consist primarily of benthic and pelagic crustaceans, and fish [@Murie_diet_1995]. The body coloring or adult `r spp` is brown with yellow to orange blotching and light-colored dorsal saddle patches [@loveetal_2002]. As their name suggests, `r spp` have long dorsal fin spines.

Limited studies have been performed looking at genetic variation in `r spp` across the U.S. West Coast. Genetic work has revealed significant differences between Puget Sound and coastal stocks of `r spp` [@seeb_gene_1998; @Stoutetal_DPS_2001], however [@seeb_gene_1998] did not find significant differentiation in populations of `r spp` between Washington and Alaska when Puget Sound samples were excluded. Significant population sub-division along the U.S. West Coast has been detected for the closely related, and more well-studied copper rockfish (*Sebastes caurinus*), indicating limited oceanographic exchange among geographically proximate locations [@seeb_gene_1998; @buonaccorsi_population_2002; @johansson_influence_2008]. High site-fidelity [@HannahandRankin_rockfish_site_fidelity_2011] and relatively small home ranges [@tolimieri_home_2009] for `r spp` suggests similar patterns of isolation-by-distance as found for other rockfish.

`r Spp` are a long-lived rockfish estimated to live up to 95 years [@loveetal_2002; @YamanakaandLacko_rockfish_2001]. `r Spp` was determined to have a vulnerability (V = 2.22) of major concern in a productivity susceptibility analysis [@cope_approach_2011].  

## Ecosystem Considerations

[Replace text if want to / have to include]


## Historical and Current Fishery Information

`r Spp` off the coast of `r state` are primarily caught in both the commercial and recreational fisheries (Table \ref{tab:catch} and Figure \ref{fig:catch}). The landings from the commercial fishery extend back to 1892 and other than an increase in the late 1930s through the 1940s, were minimal until the late-1960s. Currently, `r spp` is one of several rockfish species targeted by a nearshore, primarily live-fish fixed-gear fishery centered on `r state`'s southern coast. Following the development of the nearshore commercial fishery in the late 1990s, ODFW implemented a state-permitted limited access fishery that regulated fleet size, period landing limits, and established harvest guidelines [@rodomsky_2019_2020]. `r Spp` is one of 11 species in the Other Nearshore Rockfish category managed under a single state harvest guideline. Within this management category, China, quillback, and copper rockfish are the three primary species landed. Landings from the recreational fishery off the coast of `r state` began in 1979 and removals from the recreational fleet have increased across time and now represent the majority of landings for `r spp` off the coast of `r state`. Recreational landings were large in the year that data were first available, and were expected to be minimal prior to the 1970s. Consequently a linear ramp in recreational landings was applied from 1970 to 1979.


## Summary of Management History and Performance

`r Spp` is managed by the Pacific Fishery Management Council (PFMC) as a part of the Nearshore Rockfish North and Nearshore Rockfish South complexes. The North and South complexes are split at N. 40$^\circ$ 10' Lat. N. off the U.S. West Coast. Each complex is managed based on a complex-level overfishing limit (OFL) and annual catch limit (ACL). The OFL and ACL values for the complexes are determined by summing the species specific OFLs and ACLs managed within each complex. Removals for species within each Nearshore complex are managed and tracked against the complex total OFL and ACL, rather than on a species by species basis.

`r Spp` was most recently assessed in 2010 using Depletion-Based Stock Reduction Analysis (DB-SRA) to provide estimates of coastwide OFLs ([@DickandMacCall_dbsra_2010]). The coastwide OFL was then apportioned to each management area based on the proportion of historical catches North and South of 40$^\circ$ 10' Latitude. DB-SRA does not assess overfished status, but assuming that current depletion was at the management target on average (e.g. 40%), the 2010 assessment found that `r spp` had a 52% chance of experiencing overfishing, in that recent coastwide catch of `r spp` slightly exceeded the median coastwide OFL estimate. 

The current OFL and ACLs for `r spp` North of 40$^\circ$ 10' Lat. N., the state/specific ACL allocation (58.4% for `r state`; Groundfish Management Team, pers. comm.), and the total removals are shown in Table \ref{tab:ofl}.
