## Fishery-Dependent Data

### Commercial Fishery

Commercial landings data from 1892 to 2020 were provided by the Oregon Department of Fish and Wildlife (ODFW). State description of recreational removal data --- To be provided by Ali. 

The input catches in the model represent total removals: landings plus discards.  Therefore, discards were calculated and added to the landings data provided by ODFW. Discard totals for the commercial fleet from 2002-2019 were calculated based on West Coast Groundfish Observer Program (WCGOP) data provided in the Groundfish Expanded Mortality Multiyear (GEMM) product. The total coastwide observed discards from the GEMM were allocated to Oregon based on the ratio of total observed landings by state combined across gears (fixed and trawl) to total observed landings coastwide, as observed by WCGOP. Discards for the commercial fleet from 1990-2001 were calculated as a proportion of the landings, where the proportion equaled the average discard rates from fixed-gear only from 2002-2019 and was 5.7 percent. Discards from 1990-2001 were calculated using fixed-gear observations because trawl landings were high in the 2000s but low in the 1990s. Discards prior to 1990 were assumed to be zero given some active targeting occurred and were prior to state and federal regulations for rockfishes.  

The commercial removals of `r spp` were relatively small prior to 1940, the first year the removals were greater than 0.50 mt (Figure \ref{fig:catch}). Since 2000, the commercial removals on average are approximately one third of the total removals.

Commercial length composition data is available starting in 1998 (Table \ref{tab:com-len-samps}). The lengths observed by the commercial fishery range between 20 - 50 cm (the maximum length data bin size, Figure \ref{fig:com-len-data}). The mean size observed by the commercial fishery varied from year to year with the mean length occurring between 34 - 40 cm for all but the first two years, which had small sample sizes and were 26.5 and 29 cm (Figure \ref{fig:mean-com-len-data}). 

The input sample sizes were calculated via the Stewart method (Ian Stewart, personal communication) which incorporate the number of trips and fish by year:

\begin{centering}

Input effN = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $<$ 44

Input effN = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $\geq$ 44

\end{centering}


### Recreational Fishery

Recreational landings data from 1979 to 2020 were provided by the Oregon Department of Fish and Wildlife (ODFW). State description of recreational removal data --- To be provided by Ali.

The input catches in the model used from 2001-2020 were obtained from RecFIN and represent total removals consisting of both landings and estimated discard mortality. The removals for 2000 and prior were obtained from the ODFW Sport Reconstruction. No recreational discarding was assumed for these earlier years because the bag limits (15 fish bag limit) are thought not to have been restrictive enough to induce appreciable size-based discarding of `r spp`.

The first year of recreational removals in the model was 1970. Recreational removal data provided by ODFW started in 1979 at nearly 4 mt. It was assumed that some recreational effort for `r spp` occurred prior to 1979 but was negligible before 1970. Therefore, catch was linearly interpolated to zero between 1979 and 1970. Since 2000, recreational removals for have steadily increased, except for 2015 and 2016 where retention was regulated, and peaked in 2018 at a total of `r max(model$catch[model$catch$Fleet==2,"Obs"])` mt. Recreational removals are the main source of exploitation of `r spp` in Oregon waters (Figure \ref{fig:catch}).

Length compositions data for the recreational fleet was available from 1980 - 2020, with the exception of 1990-1992 (Table \ref{tab:len-samps}). The number of length observations by year were relatively small prior to 2001 compared to years after, and contributed to less well defined length distributions (Figure \ref{fig:rec-len-data}). The lengths observed by the recreational fishery range between 18 - 50 cm. The mean length by year in the recreational data was generally larger and more variable prior to 1999, after which the mean lengths observed by year became relatively stable with tight 95 percent confidence intervals (Figure \ref{fig:mean-rec-len-data}).

The input sample sizes for the recreational length data were calculated equal to the number of length samples available by year. 