### \acrlong{s-wcgbt}

Information from the West Coast Groundfish Bottom Trawl Survey (WCGBTS) was used to calculate biological parameters including growth and weight-at-length relationships. An index of abundance was not calculated due to small sample size, and consequently, length composition data from the WCGBTS was not included in the model. 

The WCGBTS is based on a random-grid design; covering the coastal waters from a depth of 55 - 1,280 m [@bradburn_2003_2011]. This design generally uses four industry-chartered vessels per year assigned to a roughly equal number of randomly selected grid cells and divided into two 'passes' of the coast. Two vessels fish from north to south during each pass between late May to early October. This design therefore incorporates both vessel-to-vessel differences in catchability, as well as variance associated with selecting a relatively small number (approximately 700) of possible cells from a very large set of possible cells spread from the Mexican to the Canadian borders.