## Fishery-Independent Data

No fishery-independent data sources that are commonly incorporated in West Coast groundfish assessments (as required by the data moderate Terms of Reference) had adequate sample size of `r spp` off the `r state` coast to include abundance indices for this assessment. The WCGBTS, and previously the Triennial survey, collect data off the `r state` coast on rockfish biology and abundance. There were no more than ten positive tows of `r spp` in any one year coastwide in the WCGBTS, and typically fewer than five. Similarly there were no more than five positive tows of `r spp` in any one year coastwide for the Triennial survey. Given indices of abundance were not calculated due to small sample sizes, length composition data from the WCGBTS (n = 102) and Triennial Survey (n = 5) off `r state` were not included in the model. Biological data from the WCGBTS survey was used in external calculations of biological parameters, including growth and weight-at-length relationships. No ages or weights for `r spp` were available from the Triennial survey. 

`r state` has a number of state-specific small-scale fishery-independent surveys and datasets considered by ODFW to have adequate samples of `r spp`. These include two abundance estimates, one from underwater video lander data and the other from remotely-operated vehicle surveys, and a catch-per-unit-effort time series from hook and line surveys in Oregon's marine reserves network. Given these surveys are not commonly incorporated into West Coast groundfish assessments, and are not explicitly conducted as a state-wide estimate of relative or absolute abundance, we do not include the data in the model for `r spp`. However, we do compare estimates from these surveys to the our assessment model in [Appendix](#append_b).
