<!-- Base Model Results -->

```{r, echo=FALSE, results='asis'}
general_wd = "U:/Stock assessments/quillback_rockfish_2021/write_up/general_text"
filein = file.path(general_wd, '33_results_basemodel.Rmd')
read_child(filein)
```

### Parameter Estimates

Estimated parameter values are provided in Table \ref{tab:params}. The ln($R_0$) was estimated at `r round(model$parameters[model$parameters$Label == 'SR_LN(R0)', 'Value'], 2)`. The selectivity curves for the commercial and recreational fleet are shown in Figure \ref{fig:selex}. The selectivity was fixed to be asymptotic for the commercial fleet with a peak in maximum selectivity starting at `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_OR_Commercial(1)', 'Value'], 1)` cm. Selectivity for the commercial fleet was steep and nearly knife-edged. The selectivity for the recreational fleet was estimated to be dome-shaped at the largest sizes. The peak of the selectivity curve by the recreational fleet was estimated to start at `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_OR_Recreational(2)', 'Value'], 1)` cm and decline at 43 cm. 

After discussions with individuals knowledgeable about the recreational fishery, we theorized that the dome-shape in selectivity could arise due to older and larger fish moving deeper and being unavailable to the recreational fishery, which often operates nearshore and often targets rockfish in the water column, such as black or blue/deacon rockfishes, rather than quillback rockfish, which is typically strongly associated with the bottom. Additionally, in most recent years, the recreational fishery has also been restricted to extreme nearshore waters (<20 – 40fm) to reduce impacts on overfished rockfishes, primarily yelloweye rockfish. Sensitivities to the shape and potential time blocking of the recreational selectivity were explored (see below in Section \ref{sensitivity-analyses}). 

The estimated annual recruitment and recruitment deviations are shown in Figures \ref{fig:recruits} and \ref{fig:rec-devs}. Strong recruitment events were estimated to have occurred in 1993, 1995, 1999, and 2012 which resulted in a substantial increase in biomass during the late 1990s and early to mid 2000s. While the largest recruitment deviations were estimated to have occurred in these four specific years, the surrounding years in the 1990s also have above average recruitment estimated, whereas the surrounding years in the 2000s have lower than average recruitment estimated. Bias adjustment was applied to the annual estimates of recruitment deviations following the pattern of transformed variances in recent years as shown in Figure \ref{fig:bias-adj}.

The large recruitment pulses in the 1990s show up in the composition data for the commercial and recreational fleets in some years as a pulse of young fish, but more so as a steady increasing trend in mean size that help support the increasing catches over the time. The steadily increasing mean size in the recreational fleet along with minimal catches of smaller fish in the composition data supports the estimated below average recruitment in the 2000s, until 2012. The 2012 large recruitment pulse shows up in the composition data for both the commercial and recreational fleets as pulses of smaller fish that are also reflected by declines in mean size. 

### Fits to the Data

Fits to the length data are shown based on the Pearson residuals-at-length, the annual mean lengths, and aggregated length composition data for the commercial and recreational fleets. Fits to the length composition data by year are provided in [Appendix A](#append_a).

The Pearson residuals for the commercial fishery have no discernible pattern of misfit to the length data across cohorts but show areas of misfit over time (Figure \ref{fig:com-pearson}). The residuals show that the peak of the composition is being underfit for many years. These years have lower sample size, and for years with high sample size such as 2000, 2002, and 2017, compositions are being fit well. The largest residuals were observed in 1999 or when missing small spikes of small fish in the compositions (2009, 2017, 2020) (see [Appendix A](#append_a) for details). The mean lengths observed by the commercial fishery were variable by year but with generally consistent confidence intervals across years and showed an increase in mean length followed by a period of stability and then decline (Figure \ref{fig:com-mean-len-fit}). 

The Pearson residuals for the recreational length data were variable by year and indicate no discernible pattern of misfit to the length data (Figure \ref{fig:rec-pearson}). A period of positive residuals from 2005-2014 show that the peak of the composition is being underfit, however visual inspections suggest overall good fit (see [Appendix A](#append_a) for details). The residual patterns for 2017-2020, which are the largest residuals outside misfits to very high and very low lengths in low sample size years (before 1990), show the model has difficulty fitting the bimodal patterns in these years, which is not unexpected. Throughout the mid-2000s the mean length increases to a larger size (around 40 cm in 2015) with a substantial decrease in variation of the observed lengths compared to pre-2000 lengths (Figure \ref{fig:rec-mean-len-fit}). The mean length was highly uncertain in 2015 due to low sample size (Table \ref{tab:len-samps}) 

Aggregate fits by fleet are shown in Figure \ref{fig:agg-len-fit}. The model fits the aggregated lengths for the recreational fleet well. The fit to the commercial fleet is poorer. Both fleets show similar ranges of sizes measured and an aggregated peak around 40 cm. The commercial fleet shows proportionally less catch of intermediate size fish between 30-40 cm compared to the recreational fleet. The model overfits the proportion of intermediate fish in the commercial fishery and underestimates the proportion of fish selected at their peak. The poor fit to commercial aggregate lengths appears to be due to periods with catches of small fish (1999-2002, and 2015-2020) that contribute to the peak at small sizes, and periods of catches of larger fish (2003-2014) that contribute to the peak at larger sizes. The periods where small fish were caught correspond to years where estimated large recruitments would appear in the catch. The base model fits the data best with a very steep selectivity curve for the commercial fleet, matching the left edge of aggregate composition for the commercial fleet (Figure \ref{fig:agg-len-fit}). The near knife-edge selectivity at small sizes was somewhat unexpected given that along with longline gear, commercial fishing occurs on hook and line similar to the hook and line gear used in the recreational fleet. Thus, peak selectivity nearer to the estimate for the recreational selectivity was expected. A sensitivity blocking commercial length compositions in years without bimodal distributions (2003-2014) was explored to see the effect of these years on estimates of selectivity for the commercial fishery.      
 

### Population Trajectory

The predicted spawning output (in millions of eggs) is given in Table \ref{tab:timeseries} and plotted in Figure \ref{fig:ssb}. The estimates of spawning output across time are uncertain with the base model estimating a spawning output of `r round(model$derived_quants[model$derived_quants$Label == 'SSB_2021','Value'], 2)` in `r endyr+1` with a 95 percent asymptotic confidence interval ranging from `r paste(round(sb_low,2), "-", round(sb_high,2))` millions of eggs. The predicted spawning output from the base model declines until 1995, and steadies due to several above average recruitment events that occurred in the early- to mid-1990s. The population then increases dramatically in the early 2000s due to the very large recruitment event in 1995. The population increase slows in the late 2000s, and then declines in the 2010s due to below average recruitment through the 2000s. The estimate of total biomass over time is shown in Figure \ref{fig:tot-bio}.

The `r endyr+1` spawning output relative to unfished equilibrium spawning output is above the target of 40 percent of unfished spawning output (`r round(model$derived_quants[model$derived_quants$Label == 'Bratio_2021','Value'], 2)`, Figure \ref{fig:depl}). Approximate 95% confidence interval based on the asymptotic variance estimates show that the uncertainty in the estimated spawning output is large, ranging between approximately 20 - 75 percent of unfished equilibrium spawning output.

The slight dome shape in the final selectivity for the recreational fleet results in a fraction of large fish being unavailable in recent years (Figure \ref{fig:unavail-bio}). The fraction of large fish unavailable averaged five percent of the overall biomass since 1970, and in theory would be available for selection from the commercial fishery, which has asymptotic selectivity.  

The stock-recruit curve resulting from a value of steepness fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"],2)` is shown in Figure \ref{fig:bh-curve}. The estimated annual recruitment is shown in Figure \ref{fig:recruits}.

