# Management 

### Reference Points

Reference points were calculated using the estimated selectivity and catch distributions among fleets in the most recent year of the model (`r endyr`, Table \ref{tab:referenceES}). Sustainable total yields  were `r round(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $SPR_{50\%}$ reference harvest rate. The spawning output equivalent to 40 percent of the unfished spawning output ($SB_{40\%}$) was `r round(model$derived_quants[model$derived_quants$Label == 'SSB_SPR', 'Value'], 2)` millions of eggs. 

The `r endyr+1` spawning output relative to unfished equilibrium spawning output is above the target of 40 percent of unfished spawning output (Figure \ref{fig:depl}). The fishing intensity, $1-SPR$, has been above the harvest rate limit ($SPR_{50\%}$) in nearly all years from 1977-2001, and in all but 2015 and 2016 since 2011 (Table \ref{tab:timeseries} and Figure \ref{fig:1-spr}). Figure \ref{fig:phase-plot} shows the phase plot of relative spawning output and fishing intensity. Table \ref{tab:referenceES} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield} shows the equilibrium curve based on a steepness value fixed at `r model$parameters[model$parameters$Label == "SR_BH_steep","Value"]`.


## Harvest Projections and Decision Tables

A ten year projection of the base model was estimated for years 2023-2032, with catches equal to the estimated Acceptable Biological Catch (ABC) based on the category 2 time-varying sigma and $P^*$ = 0.45 for years 2023-2032 (Table \ref{tab:project}). The removals in 2021 and 2022 were set based on recommended values from the PFMC Groundfish Management Team (GMT, personal communication). The removals for 2023-2032 were apportioned to recreational and commercial catches based on the apportionment of the GMT provided 2022 catches, which was 60% recreational and 40% commercial. 

The axis of uncertainty for the decision table was based on a low and high state of nature for alternative values of unfished recruitment (ln($R0$)). Following guidance from the TOR, the 12.5 and 87.5 percentiles (i.e. 1.15 standard deviations) of spawning output in 2021, based on the uncertainty around the spawning output in 2021 ($\sigma$ = `r round(model$Pstar_sigma,2)`), were used to determine the values of ln($R0$) corresponding to the states of nature. Once the values of 2021 spawning output at the 12.5 and 87.5 percentiles were identified, a search across unfished recruitment values was done to obtain the identified spawning output values. The values of ln($R0$) corresponding to the low and high states of nature were 2.01 (low) and 2.28 (high). 

The same catch values from the base model projections were applied to the low and high states of nature to provide a range of projected catch quantities given alternative assumptions for ln($R0$) (Table \ref{tab:decision-table}). Across alternative states, the fraction of unfished at the end of the 10 year projection period ranges 0.34 - 0.60. Under the low state of nature, fraction of unfished is below the management target, but above the management limit, after 10 years.    

<!-- Evaluation of Scientific Uncertainty -->

```{r, echo=FALSE, results='asis'}
filein = file.path(general_wd,'4_management_uncertainty.Rmd')
read_child(filein)
```

# Research and Data Needs

The ability to estimate additional process and biological parameters for `r spp` was limited by data.  Collecting the following data would be beneficial to future assessments of the stock:

\begin{itemize}

	\item Continue collecting length and otolith samples from recreational and commercial catches, as well as from surveys, which capture small `r spp`.

	\item Improved understanding of where recreational fishing is commonly occurring (areas and depths) and the range of sizes available by depth would be beneficial to better inform the selectivity form.  
	
	\item Recruitment patterns showed lower than average recruitment in the 2000s. Additional data to support such patterns in recruitment would provide additional support for model estimates.  
	
\end{itemize}