\clearpage
# Figures


<!-- ====================================================================== -->  
<!-- ****************** Catches Used in the Model ************************* --> 
<!-- ====================================================================== -->  

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "catch2 landings stacked.png"), 
caption = "Total removals (mt) by fleet used in the base model",
label = 'catch',
alt_caption = "Stacked barchart showing landings in each year for two fleets")
```	


<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "data_plot.png"), 
caption = "Summary of data sources used in the base model",
label = 'data-plot',
alt_caption = "Dot plot indicating the years where catch and length composition data were available for each fleet")
```	


<!-- ====================================================================== -->
<!-- ****************   Commercial Length Samples    ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt1mkt0_page2.png"), 
caption = "Length composition data from the commercial fleet",
label = 'com-len-data',
alt_caption = "Bubble plot indicating quantity of data by length bin in each year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_OR_Commercial.png"), 
caption = "Mean length for commercial fleet with 95 percent confidence intervals",
label = 'mean-com-len-data',
alt_caption = "Thin box plot showing mean and confidence intervals of length data in each year")
```


<!-- ====================================================================== -->
<!-- **************** Recreational Length Samples    ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt2mkt0_page3.png"), 
caption = "Length composition data from the recreational fleet",
label = 'rec-len-data',
alt_caption = "Bubble plot indicating quantity of data by length bin in each year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_OR_Recreational.png"), 
caption = "Mean length for recreational fleet with 95 percent confidence intervals",
label = 'mean-rec-len-data',
alt_caption = "Thin box plot showing mean and confidence intervals of length data in each year")
```

<!-- ====================================================================== -->
<!-- *************************     Biology     **************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio6_maturity.png"), 
caption = "Maturity as a function of  length",
label = 'maturity',
alt_caption = "Line plot of the logistic shaped maturity-at-length relationship")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio9_fecundity_len.png"), 
caption = "Fecundity as a function of length",
label = 'fecundity',
alt_caption = "Line plot showing fecundity increase as a power function of length")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "Length_Weight_by_Sex_ForReport.png"), 
caption = "Observed sex-specific (red is female, blue is male, gray is unsexed) weight-at-length data from the individual sources with length and weight data, along with all sources combined with the estimated weight-at-length curves",
label = 'len-weight-survey',
alt_caption = "Four-panel dot plot showing the power-function shape of weight and length data across all data sources with the relationship plotted, and individually for the recreational, commercial, and survey data")
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio5_weightatsize.png"), 
caption = "Weight-at-length relationship used in the model",
label = 'len-weight',
alt_caption = "Line plot showing weight increase as a power function of length")
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "Length_Age_by_Sex_ForReport.png"), 
caption = "Observed sex-specific (red is female, blue is male, gray is unsexed) length-at-age data from the individual sources with length and age data, along with all sources combined with the estimated length-at-age curves",
label = 'len-age-data',
alt_caption = "Four-panel dot plot showing an increasing and then plateauing shape of length and age data across all data sources with the relationship plotted, and individually for the recreational, commercial, and survey data")
```	


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio1_sizeatage.png"), 
caption = "Length at age in the beginning of the year in the ending year of the model",
label = 'len-age-ss',
alt_caption = "Line plot showing length increasing and then plateauing with age")
```


<!-- ====================================================================== -->
<!-- *********************    Selectivity            ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "sel01_multiple_fleets_length1.png"),
caption = "Selectivity at length by fleet",
label = 'selex',
alt_caption = "Line plot showing the logistic-shaped pattern of selectivity and the decrease in selectivity, i.e. the dome shape, at larger sizes for the recreational fleet")
```

<!-- ====================================================================== -->
<!-- *********************    Recruitment            ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts11_Age-0_recruits_(1000s)_with_95_asymptotic_intervals.png"), 
caption = "Estimated time series of age-0 recruits (1000s)",
label = 'recruits',
alt_caption = "A whisker plot showing mean and 95 percent confidence intervals of recruitment each year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "recdevs2_withbars.png"), 
caption = "Estimated time series of recruitment deviations",
label = 'rec-devs',
alt_caption = "A whisker plot showing mean and 95 percent confidence intervals of log-recruitment deviations each year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "recruit_fit_bias_adjust_forReport.png"),
caption = "Recruitment bias adjustment applied in the base model",
label = 'bias-adj',
alt_caption = "A line plot with two lines, one showing model-estimated transformed variance by year and a second showing the suggested bias correction to apply by year")
```


<!-- ====================================================================== -->
<!-- ****************** Fit to the Length Data **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt1mkt0_page2.png"), 
caption = "Pearson residuals for commercial fleet. Closed bubble are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'com-pearson',
alt_caption = "Bubble plot of residuals by length bins in each year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_OR_Commercial.png"), 
caption = "Model estimated mean length in cm (blue line) overlaid on mean length of commercial lengths (gray circles) with 95 percent confidence intervals based on current samples sizes",
label = 'com-mean-len-fit',
alt_caption = "Box and whisker plot of mean length for each year that commercial length data were available, along with a line of model-fitted mean length")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt2mkt0_page3.png"), 
caption = "Pearson residuals for recreational fleet. Closed bubble are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'rec-pearson',
alt_caption = "Bubble plot of residuals by length bins in each year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_OR_Recreational.png"), 
caption = "Model estimated mean length in cm (blue line) overlaid on mean length for recreational lengths (gray circles) with 95 percent confidence intervals based on current samples sizes",
label = 'rec-mean-len-fit',
alt_caption = "Box and whisker plot of mean length for each year that recreational length data were available, along with a line of model-fitted mean length")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit__aggregated_across_time.png"), 
caption = "Aggregated length comps over all years",
label = 'agg-len-fit',
alt_caption = "Two-panel density plot of length data with a line showing the model estimated density, where the top panel is for commercial data and the bottom panel is for recreational data")
```

<!-- ====================================================================== -->
<!-- ******************      Time Series       **************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts7_Spawning_output_with_95_asymptotic_intervals_intervals.png"), 
caption = "Estimated time series of spawning output (million of eggs)",
label = 'ssb',
alt_caption = "Line plot of spawning output by year, with lines for 95 percent confidence interval")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts1_Total_biomass_(mt).png"), 
caption = "Estimated time series of total biomass",
label = 'tot-bio',
alt_caption = "Line plot of total biomass by year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts9_Relative_spawning_output_intervals.png"), 
caption = "Estimated time series of relative spawning output",
label = 'depl',
alt_caption = "Line plot of fraction of unfished, with lines for 95 percent confidence interval")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "UnavailableSpawningOutput.png"),
caption = "Proportion of biomass unavailable due to selectivity for small and large fish.",
label = 'unavail-bio',
alt_caption = "Four-panel figure showing different visualizations of unselected fish. The first panel is of spawning output by year for all fish, unavailable small fish, and unavailable large fish. The second panel is a line plot of the proportion of total unavailable fish by year that is made up of small and large fish. The third panel is a bubble plot showing the size of the year classes made up by unavailable small and large fish in each year. The fourth panel shows the steeply increasing selectivity-at-age pattern repeated for each year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SR_curve.png"), 
caption = "Stock-recruit curve. Point colors indicate year, with warmer colors indicating earlier years and cooler colors in showing later years",
label = 'bh-curve',
alt_caption = "Dot plot showing estimates of recruitment and spawning output in each year along with a curve showing the estimated recruitment relationship")
```


<!-- ====================================================================== -->
<!-- ******************      Likelihoods      ***************************** --> 
<!-- ====================================================================== -->

<!-- R0 -->
```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_SR_LN(R0)"),  "piner_panel_SR_LN(R0).png"), 
caption = "Change in the negative log-likelihood across a range of ln(R0) values",
label = 'r0-profile',
alt_caption = "Two-panel line plot showing the change of three components of likelihood across a range of values. In the top panel the components are total, length, and recruitment. In the bottom panel the components are elements  of the length likelihood, and are broken down into total, recreational, and commercial")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_SR_LN(R0)"),  "SR_LN(R0)_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of ln(R0) values",
label = 'r0-ssb',
alt_caption = "Line plot showing different trajectories of spawning output by year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_SR_LN(R0)"),  "SR_LN(R0)_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of ln(R0) values",
label = 'r0-depl',
alt_caption = "Line plot showing different trajectories of fraction of unfished by year")
```

<!-- h -->
```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_SR_BH_steep"),  "piner_panel_SR_BH_steep.png"), 
caption = "Change in the negative log-likelihood across a range of steepness values",
label = 'h-profile',
alt_caption = "Two-panel line plot showing the change of three components of likelihood across a range of values. In the top panel the components are total, length, and recruitment. In the bottom panel the components are elements  of the length likelihood, and are broken down into total, recreational, and commercial")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_SR_BH_steep"),  "SR_BH_steep_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of steepness values",
label = 'h-ssb',
alt_caption = "Line plot showing different trajectories of spawning output by year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_SR_BH_steep"),  "SR_BH_steep_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of steepness values",
label = 'h-depl',
alt_caption = "Line plot showing different trajectories of fraction of unfished by year")
```

<!-- M -->
```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_NatM_p_1_Fem_GP_1"),  "piner_panel_NatM_p_1_Fem_GP_1.png"), 
caption = "Change in the negative log-likelihood across a range of natural mortality values",
label = 'm-profile',
alt_caption = "Two-panel line plot showing the change of three components of likelihood across a range of values. In the top panel the components are total, length, and recruitment. In the bottom panel the components are elements  of the length likelihood, and are broken down into total, recreational, and commercial")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_NatM_p_1_Fem_GP_1"),  "NatM_p_1_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of natural mortality values",
label = 'm-ssb',
alt_caption = "Line plot showing different trajectories of spawning output by year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_NatM_p_1_Fem_GP_1"),  "NatM_p_1_Fem_GP_1_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of natural values",
label = 'm-depl',
alt_caption = "Line plot showing different trajectories of fraction of unfished by year")
```

<!-- Linf -->
```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_L_at_Amax_Fem_GP_1"),  "piner_panel_L_at_Amax_Fem_GP_1.png"), 
caption = "Change in the negative log-likelihood across a range of maximum length values",
label = 'linf-profile',
alt_caption = "Two-panel line plot showing the change of three components of likelihood across a range of values. In the top panel the components are total, length, and recruitment. In the bottom panel the components are elements  of the length likelihood, and are broken down into total, recreational, and commercial")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_L_at_Amax_Fem_GP_1"),  "L_at_Amax_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of maximum length values",
label = 'linf-ssb',
alt_caption = "Line plot showing different trajectories of spawning output by year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_L_at_Amax_Fem_GP_1"),  "L_at_Amax_Fem_GP_1_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of maximum length values",
label = 'linf-depl',
alt_caption = "Line plot showing different trajectories of fraction of unfished by year")
```

<!-- k -->
```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_VonBert_K_Fem_GP_1"),  "piner_panel_VonBert_K_Fem_GP_1.png"), 
caption = "Change in the negative log-likelihood across a range of k values",
label = 'k-profile',
alt_caption = "Two-panel line plot showing the change of three components of likelihood across a range of values. In the top panel the components are total, length, and recruitment. In the bottom panel the components are elements  of the length likelihood, and are broken down into total, recreational, and commercial")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_VonBert_K_Fem_GP_1"),  "VonBert_K_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of k values",
label = 'k-ssb',
alt_caption = "Line plot showing different trajectories of spawning output by year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_VonBert_K_Fem_GP_1"),  "VonBert_K_Fem_GP_1_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of k values",
label = 'k-depl',
alt_caption = "Line plot showing different trajectories of fraction of unfished by year")
```

<!-- CV-old -->
```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_CV_old_Fem_GP_1"),  "piner_panel_CV_old_Fem_GP_1.png"), 
caption = "Change in the negative log-likelihood across a range of CV at maximum length values",
label = 'cv2-profile',
alt_caption = "Two-panel line plot showing the change of three components of likelihood across a range of values. In the top panel the components are total, length, and recruitment. In the bottom panel the components are elements  of the length likelihood, and are broken down into total, recreational, and commercial")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_CV_old_Fem_GP_1"),  "CV_old_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of CV at maximum length values",
label = 'cv2-ssb',
alt_caption = "Line plot showing different trajectories of spawning output by year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_CV_old_Fem_GP_1"),  "CV_old_Fem_GP_1_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of CV at maximum length values",
label = 'cv2-depl',
alt_caption = "Line plot showing different trajectories of fraction of unfished by year")
```


<!-- ====================================================================== -->
<!-- ******************     Retrospectives    ***************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_retro"),  "compare2_spawnbio_uncertainty.png"), 
caption = "Change in the estimate of spawning output when the most recent 5 years of data are removed sequentially",
label = 'retro-ssb',
alt_caption = "Line plot showing different trajectories of spawning output by year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_retro"),  "compare4_Bratio_uncertainty.png"),
caption = "Change in the estimate of fraction unfished when the most recent 5 years of data are removed sequentially",
label = 'retro-depl',
alt_caption = "Line plot showing different trajectories of fraction of unfished by year")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_retro"),  "compare11_recdevs.png"),
caption = "Change in the estimate of annual recruitment deviations when the most recent 5 years of data are removed sequentially",
label = 'retro-recdevs',
alt_caption = "Dot plot showing different time series of estimated log-recruitment deviations by year")
```

<!-- ====================================================================== -->
<!-- ******************       Sensitivity     ***************************** --> 
<!-- ====================================================================== -->

```{r, echo=FALSE, results='asis'}
sens_wd = file.path("C:/Users/Brian.Langseth/Desktop/or", "sensitivities")
nm = "base.710_updated_sensitivities_compare2_spawnbio_uncertainty.png"
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated spawning output by sensitivity",
label = 'sens-ssb',
alt_caption = "Line plot showing different trajectories of spawning output by year")
```

```{r, echo=FALSE, results='asis'}
nm = "base.710_updated_sensitivities_compare4_Bratio_uncertainty.png"
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated fraction unfished by sensitivity",
label = 'sens-depl',
alt_caption = "Line plot showing different trajectories of fraction of unfished by year")
```

```{r, echo=FALSE, results='asis'}
nm = "base.710_updated_sensitivities_compare12_recdevs_uncertainty.png"
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated annual recruitment deviation by sensitivity",
label = 'sens-recdev',
alt_caption = "Whisker plot showing different time series of estimated mean and 95 percent confidence intervals of log-recruitment deviations each year")
```


<!-- ====================================================================== -->
<!-- ******************    Reference Points    **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SPR2_minusSPRseries.png"), 
caption = "Estimated 1 - relative spawning ratio (SPR) by year",
label = '1-spr',
alt_caption = "Line plot")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SPR4_phase.png"), 
caption = "Phase plot showing the fraction unfished versus fishing intensity for each year. Each point shows the spawning output relative to the unfished spawning output and the SPR ratio for each year. Lines through the final point show the 95 percent confidence intervals based on the asymptotic uncertainty for each dimension. The shaded ellipse is a 95 percent confidence region which accounts for the estimated correlations between the spawning output and SPR ratios",
label = 'phase-plot',
alt_caption = "Biplot showing sequential estimates of fishing intensity and relative biomass over time. The plot is divided into two quadrants separated by 0.4 relative biomass")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "yield2_yield_curve_with_refpoints.png"), 
caption = "Equilibrium yield curve for the base case model. Values are based on the 2020
fishery selectivity and with steepness fixed at 0.72",
label = 'yield',
alt_caption = "Line plot showing the yield corresponding to a range of fraction of unfished values from 0 to 1, with reference lines at fraction of unfished values for management reference points of 0.4 and 0.25, and model quantities of SPR target and current 2021 value")
```

\newpage