# Data
The following types and sources of data were used in this assessment. Fishery catch and composition data were specific to `r state`, however biological data were estimated coastwide and included Oregon, Washington, and California sources. 

1. Commercial landings, and length and weight data obtained from PacFIN, and the CDFW. Weight data were used to estimate biological parameters which were fixed inputs to the model.
2. Estimates of commercial discard length frequencies and fraction discarded in the fishery obtained from the West Coast Groundfish Observer Program (WCGOP).
3. Recreational landings, discards, and length and weight data obtained from the Marine Recreational Fisheries Statistics Survey (MRFSS) and the California Recreational Fisheries Survey (CRFS), which are available on the Recreational Fisheries Information Network (RecFIN). Weight data were used to estimate biological parameters which were fixed inputs to the model.
4. Historical reconstruction of commercial and recreational landings from Ralston et al. [-@ralston_documentation_2010].
5. Fishery independent biological data (length, weight, and age) from the Northwest Fisheries Science Center (NWFSC) West Coast Groundfish Bottom Trawl Survey (WCGBTS). These data were used to estimate biological parameters which were fixed inputs to the model.
6. Estimates of fecundity, maturity, and natural mortality from various sources.

A description of each data type is provided below, with timing of catch and composition data used in the base model shown in Figure \ref{fig:data-plot}.
