## Fishery-Dependent Data

### Commercial Data

#### Landings

The commercial removals for `r spp` were combined into a single fleet by aggregating across gear types and fish landed live vs. dead (Table \ref{tab:catch} and Figure \ref{fig:catch}). The grouping of all commercial landings into a single fleet was driven by the limited length composition data available per gear type. Additionally, commercial length data available in the Pacific Fisheries Information Network (PacFIN) database for California did not have the needed information to identify samples from live or dead fish (e.g., condition code) preventing the ability to evaluate the data based on live vs. dead landing. 

Commercial landings from 1916 - 1969 were queried from the SWFSC catch reconstruction database for estimates from the California Catch Reconstruction [@ralston_documentation_2010]. Landings in this database are divided into trawl, 'non-trawl', and 'unknown' gear categories, for various regions within `r state`. During the 2016 catch reconstruction workshop it was realized that catches landed at California ports but caught off Oregon and Washington between 1948-1968 were not included in the Ralston [-@ralston_documentation_2010] catch reconstructions. For rockfish species, a ratio estimator was calculated based on overall species composition from the most northern California area and applied to all rockfish market categories reported to be caught off Oregon and Washington. Catches of `r spp` were minimal and totaled approximately 0.30 mt over all years and were added to the landings from the catch reconstruction for this model.

In September 2005, the California Cooperative Groundfish Survey (CCGS) incorporated newly acquired commercial landings statistics from 1969 - 1979 into the CALCOM database. The data consisted of landing receipts ("fish tickets"), including mixed species categories for rockfish. In order to assign rockfish landings to individual species, the earliest available species composition samples were applied to the fish ticket data by port, gear, and quarter. These 'ratio estimator' landings are coded (internally) as market category 977 in the CALCOM database, and are used in this and past assessments as the best available landings for the time period 1969 - 1979 for all port complexes. Catches during this time for `r spp` are negligable. See Appendix A of Dick et al. [-@dick_status_2007] for further details.

Commercial fishery landings from 1984-2020 were pulled from the PacFIN (extracted 2/21/2021). There were no `r spp` catches in PacFIN from 1981-1984 so landings of `r spp` from 1981-1983 were set equal to the average landings from the three years before (1978 - 1980) and after (1984 - 1986) this time period. 

The input catches in the model represent total removals: landings plus discards (Table \ref{tab:catch} and Figure \ref{fig:catch}). Discards totals for the commercial fleet from 2002 - 2019 were determined based on West Coast Groundfish Observer Program (WCGOP) data provided in the Groundfish Expanded Mortality Multiyear (GEMM) product. The total coastwide observed discards were allocated to state and area based on the total observed landings observed by WCGOP. Discards were added to landings to obtain total removals for 2002-2019. Total removals prior to 2002, and for 2020 where no WCGOP data were yet available, were calculated based on the average discard rates of fixed gears from WCGOP for `r state` (3.6 percent). 


#### Length Compositions 

Available length data collected from commercial fisheries from 1978-2020 was extracted from PacFIN for `r state` `r spp` (Table \ref{tab:com-len-samps}, extracted 2/23/2021). Samples were very sparse prior to 1991 and consisted of only three samples, one each in 1978, 1984, and 1987, which were not used in model fitting (i.e. used as a 'ghost' fleet, not fit by the model but implied fits reflected in diagnostic output). Length samples were most numerous during the 1990s and since 2002 the number of lengths samples by year has been relatively low. The sizes observed from 1991 - 2002 were relatively broad, ranging from approximately 20 - 50 cm (the largest data bin; Figure \ref{fig:com-len-data}). Since approximately 2003 the range of sizes observed shrunk to around 30 - 45 cm and has tended toward larger sizes over time. This shift in observed sizes is also reflected in the mean lengths observed by year which have gone from around 35 cm to above 40 cm during this time (Figure \ref{fig:mean-com-len-data}). This shift in size could be due to shifts in fishery behavior or sampling, changes in the population demographics (e.g., lack of strong recruitment), or a combination of multiple factors. 

The input sample sizes for the commercial length data were calculated via the Stewart method (Ian Stewart, personal communication) which incorporate the number of trips and fish by year:

\begin{centering}

Input effN = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $<$ 44

Input effN = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $\geq$ 44

\end{centering}

[Describe that these were expnaded comps - and describe process]


### Recreational / Sport Data

#### Landings

Recreational landings from 1928 - 1980 were obtained from the historical reconstruction [@ralston_documentation_2010]. Recreational removals from 1981 - 1989 were obtained from Marine Recreational Fisheries Statistics Survey (MRFSS). The MRFSS dataset also includes removals in 1980 however landings from the historical reconstructions were preferred for 1980. Recreational removals from 1993 - 2020 were obtained from California Recreational Fisheries Survey (CRFS; available on the Recreational Fisheries Information Network, RecFIN). The total removals for the missing years between the MRFSS and CRFS datasets, 1990 - 1992, were assumed by applying a linear ramp in removals between the 1989 and 1993 values. Removals in 1993 were some of the largest for the recreational fleet across all years, so the effects of assuming a lower value were explored as a Sensitivity (see Section \ref{sensitivity-analyses} for details). Both data sources, MRFSS and CRFS, provide total mortality which combined observed landings plus estimates of discarded fish. Discard estimates for the recreational fleet for years between 1928 - 1980 were calculated based on the discard rate (1.7 percent) from the MRFSS and CRFS data in years 1980-2004. A direct breakdown of the landed and discarded fish by weight was not available for these years, so the proportion by number of total dead catch that was unavailable to the sampler, which included dead discarded fish, was calculated and averaged across years.  

The recreational fishery is the main source of mortality for `r spp` in `r state`. Recreational catches peaked in the late 1970s and early 1980s, apart from two year of large catches in 1984 and 1993. Removals declined sharply in 1994, but increased in the mid 2000s and in recent years. 


#### Length Compositions 

Recreational length samples from MRFSS for years 1980 - 2003 and from CRFS for years 2004 - 2020 were obtained from the RecFIN website. The lengths of fish measured by samplers onboard Commercial Passenger Fishing Vessels (CPFV) prior to being released (Type 3d data) from 2003 to 2020 were also downloaded from the RecFIN website, however this dataset only included one `r spp` so was not used. The number of length observations by year are shown in Table \ref{tab:len-samps}, with the highest number of samples occuring in years since 2004. The distribution of lengths of `r spp` observed by the recreational fleet have generally ranged between 20 - 50 cm (the maximum length data bin size) across all available years (Figure \ref{fig:rec-len-data}). Samples in years prior to 1989 generally were more uniformly distributed and had smaller samples sizes than in other years. The mean length observed each year was more variable within and among years prior to the mid 1990s, ranging from slightly above 40 cm to slightly below 30 cm (Figure \ref{fig:mean-rec-len-data}). Since 2005, mean length has been less variable across years, between 35 and 40 cm, with less variation within the year.

The input sample sizes for the recreational length data were calculated equal to the number of length samples available by year. 
