## Fishery-Independent Data

No fishery-independent data sources that are commonly incorporated in West Coast groundfish assessments (as required by the data moderate Terms of Reference) had adequate sample size of `r spp` off the `r state` coast to include abundance indices for this assessment. The WCGBTS, the Hook and Line survey, and the Triennial survey collect data off the `r state` coast on rockfish biology and abundance. There were no more than ten positive tows of `r spp` in any one year coastwide in the WCGBTS, and typically fewer than five. Similarly there were no more than five positive tows of `r spp` in any one year coastwide for the Triennial survey. No `r spp` were captured in the Hook and Line survey. Given that indices of abundance were not calculated due to small sample sizes, length composition data from the WCGBTS (n = 26) and Triennial Survey (n = 1) off `r state` were not included in the model. Biological data from the WCGBTS survey was used in external calculations of biological parameters, including growth and weight-at-length relationships. No ages or weights for `r spp` were available from the Triennial survey. 
