<!-- Base Model Results -->

```{r, echo=FALSE, results='asis'}
general_wd = "U:/Stock assessments/quillback_rockfish_2021/write_up/general_text"
filein = file.path(general_wd, '33_results_basemodel.Rmd')
read_child(filein)
```

### Parameter Estimates
Estimated parameter values are provided in Table \ref{tab:params}. The $R_0$ was estimated at `r round(model$parameters[model$parameters$Label == 'SR_LN(R0)', 'Value'], 2)`. The selectivity curves for the commercial and recreational fleet are shown in Figure \ref{fig:selex}. The selectivity was fixed to be asymptotic for the commercial fleet with a peak in maximum selectivity for fish starting at `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_CA_Commercial(1)', 'Value'], 1)` cm. The selectivity for the recreational fleet was also estimated to be asymptotic with a peak of the selectivity curve starting at `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_CA_Recreational(2)', 'Value'], 1)` cm. Sensitivities to the shape of the commercial and recreational selectivity form and potential time blocking of the recreational fleet was explored (see below in Section \ref{sensitivity-analyses}).

The estimated annual recruitment and recruitment deviations are shown in Figures \ref{fig:recruits} and \ref{fig:rec-devs}. Strong recruitment events were estimated prior to 2000 and in 2011. Recruitment deviations in 1987, 1996, and 1999 were particularly strong and resulted in an increase in biomass during the early 2000s. While the largest recruitment deviations were estimated to have occurred in these three specific years, the surrounding years in the 1980s and 1990s also have above average recruitment estimated. Recruitment deviations in the 1980s and 1990s however were highly variable, with variation extending above the value of sigmaR (0.6), suggesting recruitment during these years is not strongly informed by the data. Recruitment deviations for 1996 and 1999 were less variable, with variance below that of sigmaR, suggesting these two years were more informed by the data. Below average recruitment were estimated since 2000, with the exception of 2011. Bias adjustment was applied to the annual estimates of recruitment deviations following the pattern of increased bias adjust for recent years as shown within r4ss (Figure \ref{fig:bias-adj}).

The general pattern in recruitment deviations showed fiarly close coherence with the recruitment deviations estimated in the separate Oregon model. The Oregon base model estimated above average recruitment in the late 1990s, though for fewer years, and a strong recruitment pulse in 2012. This may potentially suggest that `r spp` off the coast of `r state` and Oregon experience similar drivers in recruitment.

The large recruitment pulses in the 1980s and 1990s primarily show up in the composition data for the commercial and recreational fleets as a steady range of sizes across years, but also as a pulse of young fish around 2000 and 2001 for the commercial and recreational fleets. The recruitment pulse in 1999 does not clearly show up as a single pulse of young fish in later years but is probably aggregated with the 1996 recruitment pulse to support the trend of increasing mean size for both the commercial and recreational fleets. The increasing mean size in the recreational and commercial fleet after 2005 along with minimal catches of smaller fish in the compositional data supports the below average recruitment in the 2000s. The 2011 recruitment pulse shows up primarily in the composition data for the recreational fleet as pulses of smaller fish in 2015-2017 that are also reflected by declines in mean size. The commercial fleet also shows some pulses of smaller fish in 2017-2018 along with declines in mean size, with the later time frame likely being due ot a right shifted selectivity curve compared to the recreational fleet. 

### Fits to the Data

Fits to the length data are shown based on the Pearson residuals-at-length, the annual mean lengths, and aggregated length composition data for the commercial and recreational fleets. The Pearson residuals for the commercial fishery have no discernible pattern of misfit to the length data across cohorts but show areas of misfit over time (Figure \ref{fig:com-pearson}). The residuals show that the peak of the composition is being underfit in many years since 2001, where sample sizes are lower and the distributions have a prominant peak (see [Appendix B](#append_b) for details). The mean lengths observed by the commercial fishery were variable by year, with higher variation since 2004 given smaller sample size, and showed an increase in mean length starting in 2007 and a decline after 2014 (Figure \ref{fig:com-mean-len-fit}). The increase in mean size estimated by the model was substantially less than the increase in mean size observed in the data, and likely a consequence of smaller sample size for commercial lengths compared to recreational lengths during this time.   

The Pearson residuals for the recreational length data were variable by year and indicate no discernible pattern of misfit to the length data (Figure \ref{fig:rec-pearson}). Positive residuals at the edges of the distribution in years before 2004 , which are the largest residuals, are indicative of widely spread distributions with lower sample size. In years since 2004, there are periods of positive and negative residuals in clustered over two to five years. The positive residuals indicate underfitting of peaked distributions (e.g. in 2006-2010, or in 2012-2014), whereas negative residuals indicate overfiting of the distribution as it skews to the left or right (e.g. 2005-2007 or 2015-2019; see [Appendix B](#append_b) for details). The mean length decreased from a high around 40cm in the early 1980s through the 1990s to under 30cm, and then increased slightly through 2004. After 2004, the variation in mean lenth was reduced, and mean leangth varied around 35cm, with increases through 2013 and decline in 2015 and 2016 (Figure \ref{fig:rec-mean-len-fit}). The mean length was highly variable in 2002 due to low sample size and a flat length distribution (Table \ref{tab:len-samps}). 

Aggregate fits by fleet are shown in Figure \ref{fig:agg-len-fit}. The model fits the aggregated lengths for both the commercial and recreational fleet well. Both fleets show similar ranges of sizes caught and a central tendency of 36 cm. The commercial fleet is more peaked compared to the recreational fleet, which has a more rounded peak around its central tendency and slight shift toward smaller sizes. The model expects a slightly higher proportion of the largest fish for both fleets relative to the data. This may indicate that the true selectivity of the recreational and commercial fleets may have some level of reduced selectivity for the largest fish (i.e. dome-shape). Sensitivities examining dome-shaped slectivity form were performed and presented in the [Sensitivity Analyses](#sensitivity-analyses) section below. 


### Population Trajectory

The predicted spawning output (in millions of eggs) is given in Table \ref{tab:timeseries} and plotted in Figure \ref{fig:ssb}. The predicted spawning output from the base model declines steadily until 1999, with the expection of a slight increase around 1990, and then increases due to several above average recruitment events that occurred in the to mid- to late-1990s. The population then increases until 2007 afterwhich it remains level until 2016 and then declines through to 2020. The estimate of total biomass over time is shown in Figure \ref{fig:tot-bio}.

The `r endyr` spawning output relative to unfished equilibrium spawning output is below the threshold of 25 percent of unfished spawning output (`r round(model$derived_quants[model$derived_quants$Label == 'Bratio_2021','Value'], 2)`, Figure \ref{fig:depl}). Approximate confidence intervals based on the asymptotic variance estimates show that the uncertainty in the estimated spawning output ranges between approximately 5 - 25 percent of unfished equilibrium spawning output. The standard deviation of the log of the spawning output in `r endyr` is `r round(model$Pstar_sigma, 2)`.

The stock-recruit curve resulting from a value of steepness fixed at `r print(model$parameters[model$parameters$Label == "SR_BH_steep","Value"],2)` is shown in Figure \ref{fig:bh-curve}. The estimated annual recruitment is shown in Figure \ref{fig:recruits}.

### Reference Points

Reference points were calculated using the estimated selectivity and catch distributions among fleets in the most recent year of the model (`r endyr`, Table \ref{tab:referenceES}). Sustainable total yields  were `r round(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $SPR_{50\%}$ reference harvest rate. The spawning output equivalent to 40 percent of the unfished spawning output ($SB_{40\%}$) was `r round(model$derived_quants[model$derived_quants$Label == 'SSB_SPR', 'Value'], 2)` millions of eggs. 

The `r endyr` spawning output relative to unfished equilibrium spawning output is below the threshold of 25 percent of unfished spawning output (Figure \ref{fig:depl}). The fishing intensity, $1-SPR$, has been above the harvest rate limit ($SPR_{50\%}$) in all years but four years from 1975-2009, and in all but three years since (Table \ref{tab:timeseries} and Figure \ref{fig:1-spr}). Table \ref{tab:referenceES} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield} shows the equilibrium curve based on a steepness value fixed at `r model$parameters[model$parameters$Label == "SR_BH_steep","Value"]`.

