## Model Diagnostics

### Convergence

Proper convergence was determined by starting the minimization process from dispersed values of the maximum likelihood estimates and adjusting phases of the estimated parameters to determine if the model found a better minimum. Starting parameters were first jittered by 10 percent. This was repeated 100 times with 64 out of 100 runs returning to the base model likelihood. A lower negative log-likelihood model fit was not found and all runs converged. When parameters were jittered by 25 percent, 57 of 100 runs returned to the base model likelihood. A lower negative log-likelihood model fit was again not found. Through the jittering done as explained and likelihood profiles (described below), we are confident that the base model as presented represents the best fit to the data given the assumptions made. There were no difficulties in inverting the Hessian to obtain estimates of variability throughout initial model attempts and all explorations resulted in a positive-definite Hessian. 

### Likelihood Profiles

Likelihood profiles were conducted for $R_0$, steepness, natural mortality, $L_{\infty}$, growth coefficient ($k$), and CV at maximum length values separately. These likelihood profiles were conducted by fixing the parameter at specific values and estimating the remaining parameters based on the fixed parameter value. 

In regards to values of $R_0$, the negative log-likelihood was minimized at a ln($R_0$) of `r round(log(model$derived_quants[model$derived_quants$Label == "Recr_Virgin",2]),2)` (Figure \ref{fig:r0-profile}). The commercial data supported lower ln($R_0$) values around 2.75 whereas the recreational data supported ln($R_0$) near the base model value. Increasing $R_0$ relative to the base model value resulted in an increase in stock scale (Figure \ref{fig:r0-ssb}) and status (Figure \ref{fig:r0-depl}). 

For steepness, values at the upper bound of 1.0 had the lowest negative log-likelihood (Figure \ref{fig:h-profile}). Assuming higher or lower steepness values than the fixed base model value of `r model$parameters[model$parameters$Label == "SR_BH_steep","Value"]` affected spawning output estimates by approximately 20% at most (Figure \ref{fig:h-ssb}), and had relatively little effect on stock status for all but the highest values (Figure \ref{fig:h-depl}). The estimated relative final stock status was below 0.25 for all but the highest value of steepness.

The negative log-likelihood profile across natural mortality supported values at the upper range of profiled values (0.12; Figure \ref{fig:m-profile}). The estimated stock trajectories assuming lower or higher natural mortality values than the base model value of `r model$parameters[model$parameters$Label == "NatM_p_1_Fem_GP_1","Value"]` varied up to 20% of the unfished and recent spawning output (Figures \ref{fig:m-ssb}). Higher values of $M$ reduced unfished spawning output but increased recent spawning output so the range of stock status varied from below the management precautionary zone (between 0.25 - 0.40) for lower values of $M$ to within and above the management precautionary zone for higher values of $M$ (Figure \ref{fig:m-depl}). 

A profile across a range of $L_{\infty}$ values was also conducted. The negative log-likelihood was minimized at 42 cm, near the fixed value of `r model$parameters[model$parameters$Label == "L_at_Amax_Fem_GP_1","Value"]`, though the negative log-likelihood for both 41 cm and 43 were greater than two units from the minimum (Figure \ref{fig:linf-profile}). The commercial data supported lower $L_{\infty}$ values, at the edge of the profiled range. The stock scale varied across alternative $L_{\infty}$ values where assuming lower values resulted in increased recent spawning output and assuming higher values resulted in increased unfished spawning output but decreased recent spawning output (Figure \ref{fig:linf-ssb}). Lower values of $L_{\infty}$ compared to the base resulted in a range of stock status from within, and above the management precautionary zone whereas higher $L_{\infty}$ resulted in greater levels of depletion (Figure \ref{fig:linf-depl}).

The negative log-likelihood profile across values of $k$ showed support for values between 0.11 and 0.14, and was minimized at 0.13, which is lower than the fixed value of `r model$parameters[model$parameters$Label == "VonBert_K_Fem_GP_1","Value"]` (Figure \ref{fig:k-profile}). The commercial data suggested lower estimate of $k$ to minimize negative log-likelihood but supported estimates between 0.10 and 0.16 while the recreational data suggested a minimum at 0.19, but supported values ranging from 0.12 to 0.23. The stock scale (Figure \ref{fig:k-ssb}) and status (Figure \ref{fig:k-depl}) increased under lower $k$ values.

Profiles for $L_{\infty}$ and $k$ indicate there may be information in the data to estimate growth parameters given that well defined minimums for each parameter exist among the profile values. Sensitivities estimating growth were performed and presented in the [Sensitivity Analyses](#sensitivity-analyses) section below. 

The negative log-likelihood profile across values for the CV at maximum length showed support for 0.08 and 0.09, with a minimum at 0.08, slightly lower than the base model value of 0.1 (Figure \ref{fig:cv2-profile}). The commercial data supported 0.08, while the recreational data supported 0.09. Higher variation around maximum length (i.e. higher values of CV) resulted in smaller unfished and recent spawning output (Figure \ref{fig:cv2-ssb}), and greater depletion (Figure \ref{fig:cv2-depl}), though differences with the base model were relatively small across profiled values.   

### Retrospective Analysis

A five-year retrospective analysis was conducted by running the model using data up to 2015, 2016, 2017, 2018, and 2019. The estimated spawning output (Figures \ref{fig:retro-ssb}) and stock status (Figure \ref{fig:retro-depl}) declined in comparison with the base model as recent years of data were removed. Removing years of data resulted in a steady decline is spawning output relative to the base model likely due to reducing the amount of information in the length comps about above average recruitment pulses (Figures \ref{fig:retro-recdevs}). 

### Sensitivity Analyses

A number of sensitivity analyses were conducted. Sensitivities were conducted as a single exploration from the base model assumptions and/or data, and were not performed in a cumulative fashion.

\begin{enumerate}
   
  \item Deterministic recruitment from the stock recruitment curve. 

  \item Data weighting according to the Francis method (Francis DW) using the weighting values shown in Table \ref{tab:dw}. 
  
  \item Data weighting according to the Dirichlet Multinomial method (DM DW) where the estimated parameters are shown in Table \ref{tab:dw}. 

  \item Estimate $L_{\infty}$.
  
  \item Estimate $k$.
  
  \item Estimate $L_{\infty}$ and $k$.

  \item Estimate the coefficient of variation in length of older fishes.

  \item Estimate natural mortality.
  
  \item Exclude composition data prior to 2004 for recreational fleet
  
  \item Exclude composition data prior to 1994 for recreational fleet

  \item Allow recreational selectivity form to be dome-shaped. 
  
  \item Allow commercial selectivity form to be dome-shaped.
  
  \item Estimate recreational selectivity block: 1979-1993 and 1994-2020 with asymptotic selectivity.  

  \item Adjust extreme catches for the commercial (in 1991) and recreational (in 1983 and 1993) fleets based on the average of the three years before and three years after the year of high catch. Adjusting recreational catches in 1993 results in changes to interpolated values in 1990-1992.     
  
\end{enumerate}

Likelihood values and estimates of key parameters from each sensitivity are available in Table \ref{tab:sensitivities}. Plots of the estimated time-series of spawning output, relative spawning output, and recruitment are shown in Figures \ref{fig:sens-ssb}, \ref{fig:sens-depl}, and \ref{fig:sens-recdev}, respectively.

The largest change from the base model occurred where large catches were adjusted downward, and when estimating natural mortality. Estimating $M$ resulted in a 24 percent lower estimate for initial spawning output and over two-fold higher estimate for recent spawning output compared to the base model. Stock status increased to above the management target of 0.4. The estimate for $M$ was 0.11, which according to the prior of Hamel [-@hamel_method_2015] would translate to a max age of around 50 years. Lowering the magnitude of large catches resulted in a 28 percent decline in unfished spawning output, but with a similar decline in recent spawning output such that stock status was similar. 

Six other sensitivities had either changes in initial spawning output near 10 percent or more, or resulted in depletion estimates within the precautionary zone (between 0.25 - 0.40). The sensitivities where recruitment deterministically followed the stock recruitment curve, and where data weighting was with the Dirichlet-Multinomial resulted in unfished spawning output increasing 10 percent, and declining 8 percent respectively, but similar stock status compared to the base model. Results for assuming deterministic recruitment were similar regardless of whether data weighting was updated. Estimating $L_{\infty}$, $k$, and $L_{\infty}$ and $k$ resulted in comparable estimates of unfished spawning output to that of the base model but higher recent spawning output. The two sensitivities estimating $k$ resulted in stock status between the target and threshold ratios, whereas the sensitivity estimating $L_{\infty}$ was slightly below 0.25 and more similar to the base model.  

All other sensitivities, including those estimating dome-shaped recruitment, resulted in similar estimates of unfished and recent spawning output, and thus had similar stock status, compared to the base model.

### Unresolved Problems and Major Uncertainties

A primary uncertainty for the `r state` `r spp` model is in treatment of growth parameters. The fixed value for k for `r spp` is on the higher end of other published studies, ranging between 0.06-0.19, and results in a low $M$/$k$ ratio, but one within the range of Beverton [-@Beverton_1992] for Sebastes. Profiles and sensitivities for $L_{\infty}$ and $k$ suggest estimating these parameters is possible, both separately and together, and result in estimates of $k$ nearer to the middle of the range of literature values and estimates of $L_{\infty}$ near to the fixed value. The choice also matters in the sense that estimating growth parameters results in a different stock status compared to the base model. Despite well defined profiles for $k$ and $L_{\infty}$, we decided to keep the fixed values in the base model given the relatively limited length composition data, concerns over whether length data on its own without age data can inform $k$, that the curve of estimated $k$ and $L_{\infty}$ values poorly fit the age and length data, and that growth estimates used in the model were based on data with young fish from the surveys to inform the estimate of $k$.

Variation in recruitment deviations remains an unresolved problem. Recruitment deviations in the 1980s and 1990s were highly variable, and variance was higher than the assumed value for $sigmaR$. We explored numerous ways to account for this, with the only solution reducing recruitment deviations to below the value of $sigmaR$ was by reducing the variability in size at older ages to very small values (~0.01). Under such a scenario, the trajectory of the population was very similar to the base model as was the pattern of stronger than average recruitment deviations in the 1980s and 1990s followed by weaker than average recruitment deviations in the 2000s. Consequently, this remains an unresolved problem that does not appear to greatly affect model results.

Lastly, catches of `r spp` were particularly high in a few years for both the recreational and commercial fleets. Although not affecting estimates of depletion, averaging out these high years of catches affected model scale and therefore estimates of sustainable yield. Changes to catches affecting model scale is true of all models that assume catch is well known, however for `r spp` in `r state` the magnitude of the reduction in catch for these years was approximately 20 percent of the total removals. Better understanding the factors contributing to these high catches as well as potential resolutions, should they be needed, would aid in ensuring catch time series and resulting estimates of sustainable yield are accurate.  


