# Management 

## Reference Points

Reference points were calculated using the estimated selectivity and catch distributions among fleets in the most recent year of the model (`r endyr`, Table \ref{tab:referenceES}). Sustainable total yields  were `r round(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $SPR_{50\%}$ reference harvest rate. The spawning output equivalent to 40 percent of the unfished spawning output ($SB_{40\%}$) was `r round(model$derived_quants[model$derived_quants$Label == 'SSB_SPR', 'Value'], 2)` millions of eggs. 

The `r endyr+1` spawning output relative to unfished equilibrium spawning output is below the threshold of 25 percent of unfished spawning output (Figure \ref{fig:depl}). The fishing intensity, $1-SPR$, has been above the harvest rate limit ($SPR_{50\%}$) in all years but four years from 1975-2009, and in all but three years since (Table \ref{tab:timeseries} and Figure \ref{fig:1-spr}). Figure \ref{fig:phase-plot} shows the phase plot of relative spawning output and fishing intensity. Table \ref{tab:referenceES} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield} shows the equilibrium curve based on a steepness value fixed at `r model$parameters[model$parameters$Label == "SR_BH_steep","Value"]`.

## Harvest Projections and Decision Tables

A ten year projection of the base model was estimated for years 2023-2032, with catches equal to the estimated Annual Catch Limit (ACL), which is based on the Acceptable Biological Catch (ABC) using the category 2 time-varying sigma and $P^*$ = 0.45 and the 40-10 harvest control rule, for years 2023-2032 (Table \ref{tab:project}). The removals in 2021 and 2022 were set based on the combined total removals averaged from 2017-2019 as specified by the PFMC Groundfish Management Team (GMT, personal communication). The removals were apportioned to recreational and commercial catches based on the average proportion from 2017-2019 that each fleet contributed to the total catch. 

The axis of uncertainty for the decision table was based on a low and high state of nature for alternative values of natural mortality ($M$). Following guidance from the TOR, the 12.5 and 87.5 percentiles (i.e. 1.15 standard deviations) of spawning output in 2021, based on the uncertainty around the spawning output in 2021 ($\sigma$ = `r round(model$Pstar_sigma,2)`), were used to determine the values of $M$ corresponding to the states of nature. Once the values of 2021 spawning output at the 12.5 and 87.5 percentiles were identified, a search across natural mortality values was done to obtain the identified spawning output values. The values of $M$ corresponding to the low and high states of nature were 0.0464 (low) and 0.0744 (high). 

The same catch values from the base model projections were applied to the low and high states of nature to provide a range of projected catch quantities given alternative assumptions for $M$ (Table \ref{tab:decision-table}). Across alternative states, the fraction of unfished at the end of the 10 year projection period ranged 0.12 - 0.39. Only under the high state of nature did the fraction of unfished go above the management limit after 10 years, and nearly reached the management target. The fraction of unfished for the base state of nature was near the management limit after 10 years.     

<!-- Evaluation of Scientific Uncertainty -->

```{r, echo=FALSE, results='asis'}
filein = file.path(general_wd,'4_management_uncertainty.Rmd')
read_child(filein)
```

# Research and Data Needs

The ability to estimate additional process and biological parameters for `r spp` was limited by data.  Collecting the following data would be beneficial to future assessments of the stock:

\begin{itemize}

  \item At the time of the assessment due to issues in California data in PacFIN (i.e., condition code) length samples landed live vs. dead from the commercial were unable to be identified. The ability to examine sample sizes and lengths from each type of landings would allow for future assessments to account for a greater range of commercial fishing behavior.
  
  \item Improved understanding of where recreational fishing is commonly occurring (areas and depths) and the range of sizes available by depth would better inform the selectivity form, which currently is the near the shape for maturity.  

	\item Age data were predominantly from Oregon and Washington waters. Collecting length and otolith samples from recreational and commercial catches in `r state` would result in samples from the entire U.S. West Coast informing growth. Otoliths from the WCGBTS survey would also help inform growth. California otoliths identified and aged during model reivews were insufficient to robustly estimate a separate California-specific length-age relationship given the limited sample size of young quillback rockfish from California. More data, particularly of young and old fish, are needed to be able to robustly estimate a California-specific growth curve and confirm whether growth of quillback rockfish differs between California and Washington and Oregon. 
	
	\item Recruitment patterns showed lower than average recruitment in the 2000s. Additional data to support such patterns in recruitment would provide additional support for model estimates. 
	
	\item Catches of `r spp` were particularly high in a few years for both the recreational and commercial fleet. Better understanding the factors contributing to these high catches as well as potential resolutions, should they be needed, would aid in ensuring catch time series are accurate.  
	
\end{itemize}


