## Fishery-Dependent Data

### Commercial Fishery

#### Landings

Historical commercial landings from 1892 to 1986 were provided by ODFW (Karnowski et al. 2014).  Historical landings were consistent but minimal (< 1 mt in all years except 1943) until the mid-1960s, at which point landings increased to a high of 3.5 mt in 1978. Primary gear types during this historical period included longline and troll gears. However, ODFW commercial samplers suggest that these troll landings were primarily landed on hook and line gear, but not separated by gear type on the fish tickets (pers. comm. M. Freeman, ODFW). 

Landings from 1987 – 1999 were compiled from a combination of PacFIN, which is the central repository for West coast commercial landings (extracted on 10/13/2020), and a separate ODFW reconstruction that delineated species-specific landings in the unspecified categories on PacFIN (e.g. URCK and POP1, ODFW 2017). `r Spp` landings from this reconstruction were substituted for the URCK and POP1 landings available from PacFIN, and added to PacFIN landings from other categories for a complete time series during this time period. Commercial landings from 2000 – 2020 are available on PacFIN (extracted on 10/13/2020 and 02/18/2021). `r Spp` is one of several rockfish species targeted by a nearshore, primarily live-fish fixed gear-fishery centered on Oregon’s southern coast. `r Spp` have been landed primarily with hook and line gear, though a substantial portion have been landed with bottom longline gear as well. Overall, 94.2% of `r spp` landings are from these two gear types (2000 – 2020). In the most recent years, longline landings have eclipsed hook and line landings. Landings from other gear types, including fish pot and trawl, are minimal relative to hook and line and longline gears and are sporadic. Commercial landings for `r spp` increased from the mid-1960s to 1974 and have since fluctuated between approximately 0.4 and 4.5 mt annually. From 2003 to 2020, landings have averaged 1.6 mt annually, and represent approximately one third of the total removals. Commercial landings were aggregated across gear types into a single fleet for the base model. 

[Discuss possible questions about differences in selectivity between the gears]

The input catches in the model represent total removals: landings plus discards (Table \ref{tab:catch} and Figure \ref{fig:catch}). Discards totals for the commercial fleet from 2002-2019 were determined based on West Coast Groundfish Observer Program (WCGOP) data provided in the Groundfish Expanded Mortality Multiyear (GEMM) product. The total coastwide observed discards in trawl and fixed gears were allocated by state and area based on the total observed landings observed by WCGOP. Discards were added to landings to obtain total removals for 2002-2019. Total removals prior to 2002, and for 2020 where no WCGOP data were yet available, were calculated using the average discard rates of only fixed gears from WCGOP for `r state` (5.7 percent). The discard rate for fixed gears was used instead of the discard rate over all gears because trawl catches were lower before the 2000s than after the 2000s, and therefore using a fixed gear discard rate for historical discards better reflected the gear in use at the time.  

#### Length Compositions

Commercial `r spp` length samples are available from PacFIN from 1998 – 2020 (Table \ref{tab:com-len-samps}, extracted 2/23/2021). Approximately 44.3% of these samples are females (n = 1,361) and 54.2% are males (n = 1,664). There were 46 unsexed fish. The majority (77.2%) are from the southern Oregon coast, centered in Port Orford (65.3%) and Gold Beach (11.9%), where the majority of permit holders for the commercial nearshore fishery are based and where most of the landings are made. The majority of length samples are from `r spp` landed live (57.4%). Additionally, special projects length samples collected from the commercial fishery are available from PacFIN from 1999 – 2001, 2003 – 2006, 2008, 2010, 2012, 2015, and 2017 – 2019 (n = 210; extracted on 12/11/2020), but were not used due to concerns over non-random sampling.  

The distribution of the lengths in the commercial data ranged between 21 - 54 cm (the maximum length data bin size, Figure \ref{fig:com-len-data}). The mean size observed by the commercial fishery was relatively variable from year to year with the mean length occuring between 35 - 41 cm for all but the first two years, where mean length was 27 and 29 cm (Figure \ref{fig:mean-com-len-data}). 

The length observations in 1998 were not fit in the base model due to very low (four) annual sample size but rather were used in the model as a 'ghost' fleet, not fit by the model but implied fits reflected in diagnostic output. The implied fit to these data from the base model are shown in [Appendix A](#append_a). 

The input sample sizes for the commercial length data were calculated via the Stewart method (Ian Stewart, personal communication) which incorporate the number of trips and fish by year:

\begin{centering}

Input effN = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $<$ 44

Input effN = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $\geq$ 44

\end{centering}

[Describe that these were expnaded comps - and describe process]


### Recreational Fishery

#### Landings

_Historic Ocean Boat Landings (1979 – 2000)_

Recently, the Oregon Department of Fish and Wildlife (ODFW) undertook an effort to comprehensively reconstruct all marine fish recreational ocean boat landings prior to 2001 (pers. comm. A. Whitman, ODFW). Reconstructed catch estimates from the Oregon Recreational Boat Survey (ORBS) improve upon estimates from the federal Marine Recreational Fisheries Statistical Survey (MRFSS), which have known biases related to effort estimation and sampling [@van_voorhees_evaluation_2000] that resulted in catch estimates considered implausible by ODFW. However, the ORBS sample estimates are known to lack the comprehensive spatial and temporal coverage of MRFSS. Addressing this coverage issue is a major part of this reconstruction. In general, the base data and methodology for these reconstructed estimates are consistent with recent assessments for other nearshore species [@dick_china_2016; @dick_bluedeacon_2018; @haltuch_lingcod_2018; @cope_cabezon_2019]. 

Prior to 2001, ORBS monitored marine species in both multi-species categories, such as rockfish, flatfish, and other miscellaneous fishes, and as individual species, such as lingcod or halibut. For this comprehensive reconstruction, four species categories were selected to reconstruct, including rockfish, lingcod, flatfish and miscellaneous, which constitute the bulk of the managed marine fish species. `r Spp` are a component of the rockfish species category. 

Category-level estimates were expanded to account for gaps in sampling coverage in two separate pathways. First, estimates from five major ports were expanded to include unsampled winter months in years lacking complete coverage. Expansions were based on available year-round sampling data and excluded years where regulations may have impacted the temporal distribution of catch.  Second, all other minor port estimates were expanded to include seasonal estimates in years lacking any sampling based on the amount of minor port catch as compared to all major port estimates. A subset of landings were sampled by ORBS for species compositions within these categories. Once category-level landings were comprehensive in space and time, species compositions were applied for the three multi-species categories, including rockfish, flatfish and miscellaneous fish. Borrowing rules for species compositions were specific to the category and determined based on a series of regression tree analyses that detailed the importance of each domain (year, month, port and fishing mode) to variability in compositions. 

Ocean boat estimates from 1979 – 2000 in numbers of fish of `r spp` from the above described methods were converted to biomass using biological samples from MRFSS (pers. comm. A. Whitman, ODFW). MRFSS biological data are available from 1980 – 1989 and 1993 – 2000. An annual average weight was applied to the total annual number of fish to obtain an annual landings estimate. Several years missing biological data (1979, 1990 – 1992) were filled in using neighboring years or interpolation. These landings in biomass were provided by ODFW and do not include an estimate of discarded fish. Landings during this time period gradually increased from 1979 to a peak of 7.1 mt in 1992, but fluctuated annually. Recreational landings were large in 1979, the year that data were first available, and were expected to be minimal prior to the 1970s. Consequently a linear ramp in recreational landings was applied from 1970 to 1979 for this assessment.   

_Modern Ocean Boat Landings (2001 – 2020)_

Recreational landings for ocean boat modes from 2001 – 2020 are available from RecFIN.  Both retained and released estimates of mortality are included, though retained mortality contributes the vast majority to total mortality. Release mortality is estimated from angler-reported release rates and the application of discard mortality rates from the PFMC.  From 2001 – 2020, landings averaged 4.6mt, ranging from 0.7 to 9.5 mt. In 2020, ocean boat landings were 6.3 mt.

_Shore and Estuary Landings (1979 – 2020)_

ODFW provided reconstructed estimates of shore and estuary landings for `r spp` from 1979 – 2020, using methodology similar to recent assessments [@berger_kelpgreenling_2015; @dick_bluedeacon_2018; @cope_cabezon_2019]. Data sources include MRFSS and the Oregon Shore and Estuary Boat Survey (SEBS). Numbers of fish were provided by MRFSS from 1980 – 1989 and 1993 – June 2003, and by SEBS from July 2003 – June 2005. An annual mode-specific average weight was applied to numbers of `r spp` from 1980 – 1989 and 1993 – 2005. Separate weights were calculated for shore and estuary boat modes, and excluded extreme outliers and imputed values. This reconstruction also applied two scaling factors to remove bias towards freshwater sampling and underestimation of estuary boats, as detailed in Dick [-@dick_bluedeacon_2018]. To estimate `r spp` landings from July – December 2005, an expansion was developed using the three year average of the ratio between the first six months of the year and the total annual landings from MRFSS and SEBS landings from 2002 - 2004. Separate expansions were developed for shore mode and estuary boat modes. A three year average (1980 - 1982) was used to estimate shore and estuary boat landings for 1979.  

The ODFW does not currently sample shore and estuary boat fishing trips, and so a 10 year average landing (1996 – 2005; 0.024 mt/year) was used to estimate shore and estuary boat landings during 2006 – 2020. Shore and estuary boat landings for `r spp` were sporadic. Shore and estuary boat landings averaged 0.07 mt annually from 1980 – 2003.

Recreational removals were aggregated across modes into a single fleet in the model (Table \ref{tab:catch} and Figure \ref{fig:catch}). Values from 2001-2020 represent total removals consisting of both landings and estimated discard mortality. No recreational discarding was assumed for the years 2000 and prior, because the bag limits (15 fish bag limit) are thought to not have been restrictive enough to induce appreciable size based discarding of `r spp`.

#### Length Compositions

Recreational length samples were obtained from two sources: MRFSS and RecFIN (ORBS). From 1980 – 1989 and from 1993 – 2000, the MRFSS program collected samples from both ocean and inland (estuary) areas. ODFW provided MRFSS samples with the addition of a column that flagged length values imputed from weights to allow for selection of directly measured values; however, sample size was limited and therefore, imputed lengths were used.  From 1980 – 1989, total lengths (mm) were collected by MRFSS, which were converted to fork length. From 1993 – 2000, fork length (mm) was collected. Length samples from 2001 – 2020 from the ORBS sampling program are available on RecFIN. All ORBS samples are by fork length (mm). The vast majority (78%) of these samples are from ocean trips, or do not distinguish inland from ocean (21%). Special projects samples collected by ODFW staff from the recreational fishery are also available from 1998 – 2001 and 2013 - 2015 (n = 150), but were not used due to concerns about non-random sampling. Table \ref{tab:len-samps} details sample sizes used by year in the base model. Retention of `r spp` was not allowed under recreational state regulations in 2015 or 2016, limiting the number of samples in those years. Furthermore, released samples (n = 121), of which 60 occurred in 2015 and 2016, were not used in length compositions for the base model.   

The distribution of the lengths in the recreational data ranged between 20 - 54 cm (the maximum length data bin size, Figure \ref{fig:rec-len-data}). The mean length by year in the recreational data was more variable prior to 2000, after which the mean lengths observed by year became relatively stable with tight 95 percent confidence intervals (Figure \ref{fig:mean-rec-len-data}).

The input sample sizes for the recreational length data were calculated equal to the number of length samples available by year. 
