\clearpage
# Figures


<!-- ====================================================================== -->  
<!-- ****************** Catches Used in the Model ************************* --> 
<!-- ====================================================================== -->  

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "catch2 landings stacked.png"), 
caption = "Catches by fleet used in the base model",
label = 'catch')
```	


<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "data_plot.png"), 
caption = "Summary of data sources used in the base model",
label = 'data-plot')
```	


<!-- ====================================================================== -->
<!-- ****************   Commercial Length Samples    ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt1mkt0_page2.png"), 
caption = "Length composition data from the commercial fleet",
label = 'com-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_OR_Commercial.png"), 
caption = "Mean length for commercial fleet with 95 percent confidence intervals",
label = 'mean-com-len-data')
```


<!-- ====================================================================== -->
<!-- **************** Recreational Length Samples    ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt2mkt0_page3.png"), 
caption = "Length composition data from the recreational fleet",
label = 'rec-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_OR_Recreational.png"), 
caption = "Mean length for recreational fleet with 95 percent confidence intervals",
label = 'mean-rec-len-data')
```

<!-- ====================================================================== -->
<!-- *************************     Biology     **************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "Length_Weight_by_Sex_ForReport.png"), 
caption = "Comparison of the length-at-weight data from the individual sources with length and weight data, and with all sources combined.",
label = 'len-weight-survey')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio5_weightatsize.png"), 
caption = "Weight-at-length by sex used in the model",
label = 'len-weight')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_fig_loc, "Length_Age_by_Sex_ForReport.png"), 
caption = "Observed sex specific length-at-age coastwide data by data source with the estimated length-at-age curve",
label = 'len-age-data')
```	


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio1_sizeatage.png"), 
caption = "Length at age in the beginning of the year in the ending year of the model",
label = 'len-age-ss')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio6_maturity.png"), 
caption = "Maturity as a function of  length",
label = 'maturity')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio9_fecundity_len.png"), 
caption = "Fecundity as a function of length",
label = 'fecundity')
```

<!-- =================== -->
<!-- ==  Need to do the following two  == -->

<!-- ```{r, results = 'asis'} -->
<!-- add_figure( -->
<!-- filein = file.path(data_fig_loc, "Length_fraction_female.png"),  -->
<!-- caption = "Fraction female by length across all available data sources", -->
<!-- label = 'len-sex-ratio') -->
<!-- ``` -->

<!-- ```{r, results = 'asis'} -->
<!-- add_figure( -->
<!-- filein = file.path(data_fig_loc, "Age_fraction_female.png"),  -->
<!-- caption = "Fraction female by age across all available data sources", -->
<!-- label = 'age-sex-ratio') -->
<!-- ``` -->


<!-- ====================================================================== -->
<!-- *********************    Selectivity            ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "sel01_multiple_fleets_length1.png"),
caption = "Selectivity at length by fleet",
label = 'selex')
```

<!-- ====================================================================== -->
<!-- *********************    Recruitment            ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts11_Age-0_recruits_(1000s)_with_95_asymptotic_intervals.png"), 
caption = "Estimated time series of age-0 recruits (1000s)",
label = 'recruits')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "recdevs2_withbars.png"), 
caption = "Estimated time series of recruitment deviations",
label = 'rec-devs')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "recruit_fit_bias_adjust.png"),
caption = "Recruitment bias adjustment applied in the base model",
label = 'bias-adj')
```


<!-- ====================================================================== -->
<!-- ****************** Fit to the Length Data **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt1mkt0_page2.png"), 
caption = "Pearson residuals for commercial fleet. Closed bubble are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'com-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_OR_Commercial.png"), 
caption = "Model estimated mean length (blue line) overlaid on mean length of commercial lengths (gray circles) with 95 percent confidence intervals based on current samples sizes",
label = 'com-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt2mkt0_page3.png"), 
caption = "Pearson residuals for recreational fleet. Closed bubble are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'rec-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_OR_Recreational.png"), 
caption = "Model estimated mean length (blue line) overlaid on mean length for recreational lengths (gray circles) with 95 percent confidence intervals based on current samples sizes",
label = 'rec-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit__aggregated_across_time.png"), 
caption = "Aggregated length comps over all years",
label = 'agg-len-fit')
```

<!-- ====================================================================== -->
<!-- ******************      Time Series       **************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts7_Spawning_output_with_95_asymptotic_intervals_intervals.png"), 
caption = "Estimated time series of spawning output (million of eggs)",
label = 'ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts1_Total_biomass_(mt).png"), 
caption = "Estimated time series of total biomass",
label = 'tot-bio')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts9_Relative_spawning_output_intervals.png"), 
caption = "Estimated time series of relative spawning output",
label = 'depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "UnavailableSpawningOutput.png"),
caption = "Proportion of biomass unavailable due to selectivity for small and large fish.",
label = 'unavail-bio')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SR_curve.png"), 
caption = "Stock-recruit curve. Point colors indicate year, with warmer colors indicating earlier years and cooler colors in showing later years",
label = 'bh-curve')
```



<!-- ====================================================================== -->
<!-- ******************    Reference Points    **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SPR2_minusSPRseries.png"), 
caption = "Estimated 1 - relative spawning ratio (SPR) by year",
label = '1-spr')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "yield2_yield_curve_with_refpoints.png"), 
caption = "Equilibrium yield curve for the base case model. Values are based on the 2020
fishery selectivity and with steepness fixed at 0.72",
label = 'yield')
```


<!-- ====================================================================== -->
<!-- ******************       Sensitivity     ***************************** --> 
<!-- ====================================================================== -->

```{r, echo=FALSE, results='asis'}
sens_wd = file.path("C:/Users/Brian.Langseth/Desktop/or", "sensitivities")
nm = "base.710_sensitivities_compare2_spawnbio_uncertainty.png"
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated spawning output by sensitivity",
label = 'sens-ssb')
```

```{r, echo=FALSE, results='asis'}
nm = "base.710_sensitivities_compare4_Bratio_uncertainty.png"
add_figure(
filein = file.path(sens_wd, nm),
caption = "Change in estimated fraction unfished by sensitivity",
label = 'sens-depl')
```

<!-- ```{r, echo=FALSE, results='asis'} -->
<!-- nm = "base.710_sensitivities_compare12_recdevs_uncertainty.png") -->
<!-- add_figure( -->
<!-- filein = file.path(sens_wd, nm), -->
<!-- caption = "Change in estimated annual recruitment deviation", -->
<!-- label = 'sens-recdev') -->
<!-- ``` -->

<!-- ====================================================================== -->
<!-- ******************      Likelihoods      ***************************** --> 
<!-- ====================================================================== -->

<!-- R0 -->
```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_SR_LN(R0)"),  "piner_panel_SR_LN(R0).png"), 
caption = "Change in the negative log-likelihood across a range of log(R0) values",
label = 'r0-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_SR_LN(R0)"),  "SR_LN(R0)_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of log(R0) values",
label = 'r0-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_SR_LN(R0)"),  "SR_LN(R0)_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of log(R0) values",
label = 'r0-depl')
```

<!-- h -->
```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_SR_BH_steep"),  "piner_panel_SR_BH_steep.png"), 
caption = "Change in the negative log-likelihood across a range of steepness values",
label = 'h-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_SR_BH_steep"),  "SR_BH_steep_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of steepness values",
label = 'h-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_SR_BH_steep"),  "SR_BH_steep_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of steepness values",
label = 'h-depl')
```

<!-- M -->
```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_NatM_p_1_Fem_GP_1"),  "piner_panel_NatM_p_1_Fem_GP_1.png"), 
caption = "Change in the negative log-likelihood across a range of female natural mortality values",
label = 'm-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_NatM_p_1_Fem_GP_1"),  "NatM_p_1_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of female natural mortality values",
label = 'm-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_NatM_p_1_Fem_GP_1"),  "NatM_p_1_Fem_GP_1_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of female natural values",
label = 'm-depl')
```

<!-- Linf -->
```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_L_at_Amax_Fem_GP_1"),  "piner_panel_L_at_Amax_Fem_GP_1.png"), 
caption = "Change in the negative log-likelihood across a range of female maximum length values",
label = 'linf-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_L_at_Amax_Fem_GP_1"),  "L_at_Amax_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of female maximum length values",
label = 'linf-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_L_at_Amax_Fem_GP_1"),  "L_at_Amax_Fem_GP_1_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of female maximum length values",
label = 'linf-depl')
```

<!-- k -->
```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_VonBert_K_Fem_GP_1"),  "piner_panel_VonBert_K_Fem_GP_1.png"), 
caption = "Change in the negative log-likelihood across a range of female k values",
label = 'k-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_VonBert_K_Fem_GP_1"),  "VonBert_K_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning output across a range of female k values",
label = 'k-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_profile_VonBert_K_Fem_GP_1"),  "VonBert_K_Fem_GP_1_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of female k values",
label = 'k-depl')
```


<!-- ====================================================================== -->
<!-- ******************     Retrospectives    ***************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_retro"),  "compare2_spawnbio_uncertainty.png"), 
caption = "Change in the estimate of spawning output when the most recent 5 years of data area removed sequentially",
label = 'retro-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "Profile_retro"),  "compare4_Bratio_uncertainty.png"),
caption = "Change in the estimate of fraction unfished when the most recent 5 years of data area removed sequentially",
label = 'retro-depl')
```


\newpage