# Summary{-}

This rebuilding analysis is for the sub-stock of `r spp` (_`r spp_latin`_) in waters off California. The analysis is based on the 2021 stock assessment [@Langseth_status_2021]. The 2021 assessment model estimated the `r spp` population to be at 14% of the unexploited equilibrium spawning output at the start of 2021. This rebuilding analysis compares the results of applying a suite of potential management actions to the stock for 2023 and beyond. 

This rebuilding analysis is an update of the one presented at the Pacific Fishery Management Council's (Council) November meeting, and incorporates the requests made by the Council during the November meeting. First, the assumed catch in 2022 was updated from 13.5 mt to 11.9 mt. Second, two SPR policies were added, at SPR = 0.55 and SPR = 0.65, as were two policies that delayed the application of constant SPR (at SPR = 0.6 and SPR = 0.7) until 2025. Third, the comparison between the base rebuilding analysis and the sensitivity rebuilding analyses with alternative assumptions about selectivity which was included in the November analysis was omitted for this report.   

The results of the analysis show that the value for $\text{T}_\text{MIN}$, the median year for rebuilding to the target level in the absence of fishing since the year of declaration (2023), is `r reb[[1]]$recovery_spec[4] + reb[[1]]$tmin `. The estimated generation time for `r spp` was estimated to be `r reb[[1]]$mean_gen` years. In conjunction with $\text{T}_\text{MIN}$ and the mean generation time, $\text{T}_\text{MAX}$ was estimated to be `r reb[[1]]$tmax `. An SPR = `r reb[[2]]$rebuild_quants["Yr=Tmid",2]` harvest rate leads to a 50% probability of recovery by $\text{T}_\text{MID}$ where $\text{T}_\text{MID}$ was `r reb[[1]]$rebuild_quants["Yr=Tmid",1]`, an intermediate year between $\text{T}_\text{MIN}$ and $\text{T}_\text{MAX}$.
