# Introduction

The 2021 stock assessment of `r spp` (_`r spp_latin`_) in California waters estimated that the California population of `r spp` in 2021 was below the Minimum Stock Size Threshold (MSST), which is 25$\%$ of unfished spawning output for rockfish stocks [@Langseth_status_2021]. The California population was estimated to have declined below MSST starting in 1992, reached it lowest values in the mid-1990s, increased to near the MSST in the 2000s and early 2010s, and declined in recent years. 

A draft rebuilding analysis was developed in 2021 based on the results of the 2021 assessment [@langseth_rebuild_2022], and was used to inform catch levels (i.e. ACLs) for 2023--2024 using an SPR = 0.55. Subsequently, it was determined that `r spp` was defined in the Groundfish Fishery Management Plan (FMP) as a coastwide stock, so `r spp` in California waters did not meet the criteria for an overfished declaration and a rebuilding plan was not required. Since the 2021 assessment, Amendment 31 to the FMP was approved by the Pacific Fishery Management Council in June 2023, recommending that `r spp` along the U.S. west coast be defined as three separate stocks corresponding to waters off Washington, Oregon, and California [@fed_registry_2023]. The recommended change to the FMP was finalized in September 2023 and the `r spp` stock off California was declared overfished in December 2023, necessitating an updated rebuilding analysis. 

Given the assumed levels of depletion for `r spp` in California waters and the need for rebuilding, a range of alternative rebuilding strategies were examined and are described in this report. This analysis contains updated estimates for removals of `r spp` in California waters in 2021--2024, and applies the alternative rebuilding strategies starting in 2025. 


# Overview of the 2021 stock assessment

The 2021 assessments of `r spp` assessed the stock as three separate populations along the U.S. west coast: Washington, Oregon, and California. These were the first assessments of `r spp` that used catch and length composition data to inform model estimates around stock size and status. The 2021 assessments were conducted using Stock Synthesis [@methot_stock_2013]. The previous assessment of `r spp`, conducted in 2010, was a coastwide assessment modeled using Depletion-Based Stock Reduction Analysis (DB-SRA) to provide estimates of coastwide overfishing limits (OFLs) based on catch data and biological information [@DickandMacCall_dbsra_2010]. DB-SRA is a catch-only method and does not assess overfished status; the 2010 assessment assumed that current depletion was distributed around the management target of 40$\%$. The 2010 assessment found there was a 52$\%$ chance that `r spp` was experiencing overfishing, as recent coastwide catch of `r spp` slightly exceeded the median coastwide OFL estimate at the time. Recent catches of `r spp` for the current assessment also exceed the annual catch limit (ACL) contributions for the species in all modeled areas. Estimates of depletion in 2021 for the populations off Washington and Oregon were above the MSST threshold, but the estimate of depletion for the population off California was 14$\%$ [@Langseth_status_2021].

California `r spp` was assessed using a single-sex model with coastwide life history parameters combined across sexes [@Langseth_status_2021]. Life history parameters were estimated externally and then fixed within the model. Natural mortality and steepness were both fixed, at the median and mean of the priors, respectively. Annual recruitment deviations were estimated within the base model. The model for `r spp` in California waters included two fishing fleets, a commercial and a recreational fleet. The majority of the removals and length composition data arose from the recreational fleet. Recreational removals peaked in the late 1970s and early 1980s, with two years of large catches in 1984 and 1993. Removals declined sharply in 1994, but increased to levels similar to the late 1970s and early 1980s during the mid 2000s and again in recent years. Commercial removals peaked in the mid to late 1990s, with one year of exceptionally large catches in 1991. Removals declined through the mid 2010s, but increased in recent years. Selectivity for the commercial and recreational fleets was specified to be asymptotic. The assessment model decision table explored uncertainty around stock size and status using lower ($M$ = 0.0464 yr$^{-1}$) and higher ($M$ = 0.0744 yr$^{-1}$) natural mortality ($M$) values relative to the base model ($M$ = 0.057 yr$^{-1}$).

Sensitivities to modeling choices, catch history, and parameter values were explored and showed general support for the base model estimates of stock status and depletion. Sensitivities to the von Bertalanffy growth coefficient ($k$, whether estimated on its own or along with $L_\infty$) and natural mortality showed that model estimates of depletion were sensitive to these parameter choices.  

# Management performance under rebuilding

No rebuilding plan exists for `r spp` in waters off the coast of California.

<!-- This is the first rebuilding plan for `r spp` in waters off the coast of California. -->

