# Results

## Rebuilding reference points

<!-- The following reference points reported below are based on assumed full removals of `r reb[[1]]$acl_matrix[1,2]` and `r reb[[1]]$acl_matrix[2,2]` mt in 2021 and 2022.  The reference points based on assuming lower removals in 2021 and 2022 are presented as sensitivities later in the results section. -->

Reference points calculated based on this rebuilding analysis are given in Table \ref{tab:ref-points}. The minimum time required for rebuilding, $\text{T}_\text{MIN}$, with no fishing (F=0) starting in 2023 was estimated to be `r reb[[1]]$recovery_spec[1] ` years, corresponding to the stock being rebuilt by `r reb[[1]]$recovery_spec[3] + reb[[1]]$tmin `, assuming the default removals for 2021 and 2022.  The mean generation time was estimated to be `r reb[[1]]$mean_gen ` years. The maximum time allowed for rebuilding, $\text{T}_\text{MAX}$, is defined as the $\text{T}_\text{MIN}$ plus the mean generation time for stocks that require more than 10 years to rebuild.  `r Spp` was unable to rebuild within 10 years so the estimated $\text{T}_\text{MAX}$ was `r reb[[1]]$tmax `. $\text{T}_\text{TARGET}$, and $\text{SPR}_\text{TARGET}$ are not specified since this is the first rebuilding plan for `r spp` and these values have not been set via the Council's process.

A rebuilding strategy is presented below and includes a rebuilding target year termed $\text{T}_\text{MID}$, which equals `r reb[[1]]$rebuild_quants[6,1]` and is the mid-point between $\text{T}_\text{MIN}$ and $\text{T}_\text{MAX}$. The Council may opt to select a $\text{T}_\text{TARGET}$ earlier or later than this $\text{T}_\text{MID}$ value based on fishery, economic, or other factors.

## Alternative harvest policy projections

Summary results from the rebuilding alternatives are presented in Table \ref{tab:reb-options}. Detailed
results are presented in Tables \ref{tab:prob-mat}-\ref{tab:rel-ssb-mat} and Figures \ref{fig:prob-fig}-\ref{fig:ssb-fig}.

The target rebuilding year based on the various rebuilding strategies ranged from `r min(reb[[1]]$rebuild_quants$Ttarget)` - `r max(reb[[2]]$rebuild_quants$Ttarget)` (Table \ref{tab:reb-options}). The probability of rebuilding by year steadily increased across the alternative SPR values with full rebuilding (reaching a probability of greater than 50%) by `r max(reb[[2]]$rebuild_quants$Ttarget)` when the lowest SPR of 0.50 was applied (Table \ref{tab:prob-mat} and Figure \ref{fig:prob-fig}). The recommended removals in 2023, the first year of rebuilding, were low ranging between `r min(round(reb[[1]]$acl_matrix[3,-c(1,8)],2))` - `r max(round(reb[[2]]$acl_matrix[3,2:6],2))` mt across strategies excluding the no-harvest strategy (Table \ref{tab:acl-mat}), with the recommended removals slowly increasing by year during the rebuilding period (Figure \ref{fig:acl-fig}). The estimated Overfishing Limits (OFLs) for each rebuilding alternative are given in Table \ref{tab:ofl-mat}. The change in spawning output by year relative to the spawning output target, 40% of unfished, under each of the alternatives are shown by year in Table \ref{tab:rel-ssb-mat} and Figure \ref{fig:rel-ssb-fig}. The harvest rate to obtain a 50% probability of recovery by $\text{T}_\text{MAX}$ corresponds to an SPR that is lower than 0.5, so is not provided in the tables. 

<!-- Reducing the assumed removals in 2021 and 2022 had only a limited impact on the estimated rebuilding by SPR rate (Table \ref{tab:reb-options-catch}). Reducing the removals in 2021 and 2022 decreased the minimum time for rebuilding ($\text{T}_\text{MIN}$) to `r reb[[2]]$recovery_spec[4] + reb[[2]]$tmin `, two years earlier compared to the initial rebuilding alternatives.  The reduction of the $\text{T}_\text{MIN}$ resulted in a decrease in the $\text{T}_\text{MAX}$ to `r reb[[2]]$tmax`. The probability of rebuilding, annual catches, OFLs, and relative spawning outputs by year are shown in Tables \ref{tab:prob-mat-catch} - \ref{tab:rel-ssb-mat-catch}.  -->


## Results for sensitivity on selectivity blocks and form

Reference points and summary results for the sensitivity rebuilding analysis that was based on a model with selectivity blocks for both the recreational and commercial fleets applied in 2001 with dome-shaped selectivity in the recent blocks are shown in Tables \ref{tab:ref-points-sens} and \ref{tab:reb-options-sens}. $\text{T}_\text{MIN}$ was one year earlier than the base rebuilding analysis, but because mean generation time was one year earlier (due to not applying uncertainty from the natural mortality states of nature), $\text{T}_\text{MAX}$ was the same as the base rebuilding analysis. Time to targets across the various rebuilding strategies occurred one to three years earlier than the base rebuilding model. Recommended removals in 2023 were also larger than the base, ranging between `r min(round(reb[[3]]$acl_matrix[3,-c(1,8)],2))` - `r max(round(reb[[4]]$acl_matrix[3,2:6],2))` mt, given the slightly higher spawning output and SPR in 2021 compared to the base model. 

The sensitivity rebuilding analysis was run without uncertainty from the states of nature, whereas the base rebuilding analysis incorporated the states of nature. The summary tables from the base rebuilding analysis without including uncertainty from the states of nature are therefore shown in Tables \ref{tab:ref-points-noStateOfNature} and \ref{tab:reb-options-noStateOfNature}. These tables allow comparison between the base analysis and the sensitivity analysis due only to differences in the underlying model and not differences in the application of the states of nature. Results from these tables show that the mean generation time is similar, and therefore $\text{T}_\text{MAX}$ for the sensitivity would be one year earlier from the base were states of nature not applied. Time to targets across the various rebuilding strategies would occur one to two years earlier than the base rebuilding model were states of nature not applied, with the exception of the $\text{T}_\text{MID}$ run which would occur four years earlier.  

Comparisons between Stock Synthesis output from the adopted base model and the sensitivity run are provided in (Figures \ref{fig:ssb-sens} - \ref{fig:Pearson-sens}). The sensitivity had slightly higher estimates of unfished spawning output (Figure \ref{fig:ssb-sens}) and similar depletion estimates (Figure \ref{fig:depl-sens}) compared to the adopted base model. Selectivity in the recent block was domed at large sizes for both the recreational and commercial fleets, and right shifted in recent years for the commercial fleet (Figure \ref{fig:selex-sens}) so the time series of information entered into the sensitivity rebuilding analysis were different from the time series entered into the base rebuilding analysis, contributing to differences in results. 

We do not consider the sensitivity model to be an improvement over the base model. The shifts in the selectivity curve for the commercial fleet in the sensitivity model fit the lower observed commercial mean lengths in the 1990s and the higher observed commercial mean lengths starting around 2010 better than the base model (Figures \ref{fig:MeanLengthFit-com-base} and \ref{fig:MeanLengthFit-com-sens}), leading to an improvement in AIC (Table \ref{tab:sens-table-withComBlock}). Fits to the recreational fleet mean length data were similar (Figures \ref{fig:MeanLengthFit-rec-base} and \ref{fig:MeanLengthFit-rec-sens}), and Pearson residuals for both fleets were not noticeably improved (Figures \ref{fig:Pearson-base} and \ref{fig:Pearson-sens}). The change in estimated commercial mean length in 2001 for the sensitivity model does not align with a shift in the commercial mean length data at that time. Furthermore, the mode and right side of the estimated aggregate length distribution from the commercial fleet are shifted right, and overestimate the proportion of larger fish on aggregate compared to the base model (Figures \ref{fig:aggLenFit-base} and \ref{fig:aggLenFit-sens}). Combined with the similarities in estimates of population scale and status, the base model is preferred due to parsimony. 
