\clearpage
# Tables

<!-- ## Rebuilding reference points and summary of alternatives -->

## Rebuilding reference points and policy projections

```{r, results = 'asis'}
# Rebuilding Reference Points Table
quants = c(round(reb[[1]]$sb0 * frac_fem, 2),
		   round(reb[[1]]$sb40 * frac_fem, 2),
		   round(reb[[1]]$sb_ass_year * frac_fem, 2),
		   reb[[1]]$recovery_spec[4],
		   reb[[1]]$recovery_spec[3],
		   reb[[1]]$tmin + reb[[1]]$recovery_spec[4],
		   reb[[1]]$mean_gen,
		   reb[[1]]$tmax,
		   reb[[1]]$tmin + reb[[1]]$recovery_spec[4],
		   "TBD",
		   "TBD",
		   round(reb[[1]]$spr_matrix[[1,2]],2))
row_names = c("SB0 (millions of eggs)",
              "SB40 (millions of eggs)",
              "SB2021 (millions of eggs)",
              "Year rebuilding begins",
              "Current year",
              "T\\textsubscript{MIN}",
              "Mean generation time (years)",
              "T\\textsubscript{MAX}",
              "T\\textsubscript{F=0}",
              "T\\textsubscript{TARGET}",
              "SPR\\textsubscript{TARGET}",
              "Current SPR (2021)")
col_names = c("Quantity", "2021 Assessment Values")
out = cbind(row_names, quants)
table_format(x = out,
             caption = 'Summary of the rebuilding reference points.',
             label = 'ref-points',
             align = 'l',
             col_names = col_names,
             escape = FALSE)
```

<!-- \input{C:/Users/Brian.Langseth/Desktop/ca/rebuilder/write_up/tex_tables/refpoints.tex} -->


<!-- ## Summary of alternatives -->

<!-- Base rebuilder -->
```{r, results = 'asis'}
# Rebuilding Reference Points Table
quants = rbind(round(reb[[1]]$acl_matrix[1:4,-1],2),
		   round(reb[[1]]$rebuild_quants$SPR,2),
		   reb[[1]]$rebuild_quants$Ttarget,
		   rep(reb[[1]]$tmax, length(reb[[1]]$rebuild_quants$Ttarget)),
		   reb[[1]]$rebuild_quants$Prebuild) # Prob by Tmax
row_names = c("2021 Assumed Removals (mt)", 
			  "2022 Assumed Removals (mt)",
			  "2023 ACL (mt)", "2024 ACL (mt)", "SPR", "T\\textsubscript{TARGET}", 
			  "T\\textsubscript{MAX}",
			  "Probability of recovery by T\\textsubscript{MAX}")

#Set the SPR = 0.5 run to be from the no-ABC-cap run because it matters
quants[,1] = c(round(reb[[2]]$acl_matrix[1:4,-1][,1],2),
               round(reb[[2]]$rebuild_quants$SPR[1],2),
               reb[[2]]$rebuild_quants$Ttarget[1],
               reb[[2]]$tmax,
               reb[[2]]$rebuild_quants$Prebuild[1]) # Prob by Tmax

#Set the SPR value for 40-10 and ABC to be "-" because it varies by year
quants[which(row_names=="SPR"),8:9] = "-"

#Add SPR = 0.55 and SPR 0.65 runs
extra = rbind(round(reb[[3]]$acl_matrix[1:4,-1],2),
	   reb[[3]]$rebuild_quants$SPR,
	   reb[[3]]$rebuild_quants$Ttarget,
	   rep(reb[[3]]$tmax, length(reb[[3]]$rebuild_quants$Ttarget)),
	   reb[[3]]$rebuild_quants$Prebuild)[,c(2,4)] # Prob by Tmax

#Set the SPR = 0.55 run to be from the no-ABC-cap run because it matters
extra[,1] = c(round(reb[[4]]$acl_matrix[1:4,-1][,2],2),
               reb[[4]]$rebuild_quants$SPR[2],
               reb[[4]]$rebuild_quants$Ttarget[2],
               reb[[4]]$tmax,
               reb[[4]]$rebuild_quants$Prebuild[2]) # Prob by Tmax

out = cbind(row_names, quants[,1], extra[,1], quants[,2], extra[,2], quants[,-c(1,2)])
col_names = c("Quantity", colnames(quants)[1], 
              colnames(extra)[1], 
              colnames(quants)[2], 
              colnames(extra)[2], 
              colnames(quants)[-c(1,2)])
col_names[9] = "Yr= T\\textsubscript{MID}"
table_format(x = out,
             caption = "Results of rebuilding alternatives based on alternative SPR targets for 50 percent probability of recovery based on the assumed removals for 2021-22. SPR for the ABC and 40-10 strategies is provided as a dash (-) because these strategies do not have a constant SPR value.",
             label = "reb-options",
             align = 'l',
             landscape = TRUE,
             col_names = col_names,
             escape = FALSE,
             font_size = 10)
```
\clearpage

<!-- Ramp down policies rebuilder -->
```{r, results = 'asis'}
# Rebuilding Reference Points Table
quants = rbind(round(reb[[1]]$acl_matrix[1:5,-1],2),
		   round(reb[[1]]$spr_matrix[3:4,-1],2), #Add SPR for 2023 and 2024
		   round(reb[[1]]$rebuild_quants$SPR,2),
		   reb[[1]]$rebuild_quants$Ttarget,
		   rep(reb[[1]]$tmax, length(reb[[1]]$rebuild_quants$Ttarget)),
		   reb[[1]]$rebuild_quants$Prebuild) # Prob by Tmax
row_names = c("2021 Assumed Removals (mt)", 
			  "2022 Assumed Removals (mt)",
			  "2023 Fixed Removals (mt), (2023 ACL for non-ramp)", "2024 Fixed Removals (mt), (2024 ACL for non-ramp)", 
			  "2025 ACL (mt)", "SPR in 2023", "SPR in 2024", "SPR in 2025", "T\\textsubscript{TARGET}", 
			  "T\\textsubscript{MAX}",
			  "Probability of recovery by T\\textsubscript{MAX} = 2066")

#Add ramp down policy for SPR 0.7
ramp70 = rbind(round(reb[[5]]$acl_matrix[1:5,-1],2),
	   round(reb[[5]]$spr_matrix[3:4,-1],2), #Add SPR for 2023 and 2024
	   round(reb[[5]]$rebuild_quants$SPR,2),
	   reb[[5]]$rebuild_quants$Ttarget,
	   rep(2066, length(reb[[5]]$rebuild_quants$Ttarget)), #Set as 2066 because its for policy with 0 catch starting in 2023
	   reb[[5]]$rebuild_quants$Prebuild) # Prob by Tmax for ramp policy (2067)
ramp70[11,] = reb[[5]]$prob_matrix[46,-1] #Set Prob by non-ramp Tmax (2066)

#Add ramp down policy for SPR 0.6
ramp60 = rbind(round(reb[[6]]$acl_matrix[1:5,-1],2),
	   round(reb[[6]]$spr_matrix[3:4,-1],2), #Add SPR for 2023 and 2024
	   round(reb[[6]]$rebuild_quants$SPR,2),
	   reb[[6]]$rebuild_quants$Ttarget,
	   rep(2066, length(reb[[6]]$rebuild_quants$Ttarget)), #
	   reb[[6]]$rebuild_quants$Prebuild) # Prob by Tmax
ramp60[11,] = reb[[6]]$prob_matrix[46,-1] #Set Prob by non-ramp Tmax (2066)


#Add ramp down policy for SPR 0.7 where catch is set above ABC
ramp702 = rbind(round(reb[[7]]$acl_matrix[1:5,-1],2),
     round(reb[[7]]$spr_matrix[3:4,-1],2), #Add SPR for 2023 and 2024           
	   round(reb[[7]]$rebuild_quants$SPR,2),
	   reb[[7]]$rebuild_quants$Ttarget,
	   rep(2066, length(reb[[7]]$rebuild_quants$Ttarget)), #Set as 2066 because its for policy with 0 catch starting in 2023
	   reb[[7]]$rebuild_quants$Prebuild) # Prob by Tmax for ramp policy (2067)
ramp702[11,] = reb[[7]]$prob_matrix[46,-1] #Set Prob by non-ramp Tmax (2066)

#Add ramp down policy for SPR 0.6 where catch is set above ABC
ramp602 = rbind(round(reb[[8]]$acl_matrix[1:5,-1],2),
	   round(reb[[8]]$spr_matrix[3:4,-1],2), #Add SPR for 2023 and 2024
	   round(reb[[8]]$rebuild_quants$SPR,2),
	   reb[[8]]$rebuild_quants$Ttarget,
	   rep(2066, length(reb[[8]]$rebuild_quants$Ttarget)), #Set as 2066 because its for policy with 0 catch starting in 2023
	   reb[[8]]$rebuild_quants$Prebuild) # Prob by Tmax
ramp602[11,] = reb[[8]]$prob_matrix[46,-1] #Set Prob by non-ramp Tmax (2066)


out = cbind(row_names, ramp60[,3], ramp602[,3], quants[,2], ramp70[,5], ramp702[,5], quants[,3])
col_names = c("Quantity", "Ramp1 SPR = .600", "Ramp2 SPR = .600",  "SPR = .600", "Ramp1 SPR = .700", "Ramp2 SPR = .700", "SPR = .700") 
table_format(x = out[-10,],
             caption = "Results of rebuilding alternatives for ramp-down strategy approaches (ramp1 and ramp2) based on applying alternative SPR targets starting in 2025 for 50 percent probability of recovery based on assumed removals for 2021-22 and fixed removals in 2023-24. Non-ramp strategies are copied from Table \\ref{tab:reb-options} and included for comparison. Catches (labeled ACLs) in 2023-2024 for non-ramp strategies were estimated based on the specified SPR value, and were not fixed.",
             label = "reb-ramp-options",
             align = 'l',
             landscape = TRUE,
             col_names = col_names,
             escape = FALSE)
```
\clearpage

## Rebuilding time series 

```{r, results = 'asis'}
out = as.data.frame(round(reb[[1]]$prob_matrix[1:46, ],3))
out[,2] = round(reb[[2]]$prob_matrix[1:46, 2],3) #Set the SPR = 0.5 run to be from the no-ABC-cap run
colnames(out)[7] = "Yr= T\\textsubscript{MID}"

#Add SPR = 0.55 and SPR 0.65 runs
extra = as.data.frame(round(reb[[3]]$prob_matrix[1:46, ],3))
extra[,3] = round(reb[[4]]$prob_matrix[1:46, 3],3) #Set the SPR = 0.55 run to be from the no-ABC-cap run
out2 = as.data.frame(append(out, list("SPR= .550" = extra[,3]), after = 2))
out3 = as.data.frame(append(out2, list("SPR= .650" = extra[,5]), after = 4))

#Add ramp policies for SPR 0.6 and 0.7
ramp60 = as.data.frame(round(reb[[6]]$prob_matrix[1:46, ],3))
ramp70 = as.data.frame(round(reb[[5]]$prob_matrix[1:46, ],3))
out4 = as.data.frame(append(out3, list("Ramp1 SPR= .600" = ramp60[,4]), after = 4))
out5 = as.data.frame(append(out4, list("Ramp1 SPR= .700" = ramp70[,6]), after = 7))

#Add ramp policies for SPR 0.6 and 0.7 where catch was set to above the ABC
ramp602 = as.data.frame(round(reb[[8]]$prob_matrix[1:46, ],3))
ramp702 = as.data.frame(round(reb[[7]]$prob_matrix[1:46, ],3))
out6 = as.data.frame(append(out5, list("Ramp2 SPR= .600" = ramp602[,4]), after = 5))
out7 = as.data.frame(append(out6, list("Ramp2 SPR= .700" = ramp702[,6]), after = 9))

table_format(x = out7,
             caption = "Probability of recovery by year for rebuilding strategies, including ramp strategies. Probabilities represent the proportion of simulations that reach the target biomass by the specified year.",
             label = "prob-mat",
             align = 'l',
             digits = 3,
             landscape = TRUE,
             col_names = c(colnames(out)[1:2], 
                           "SPR= .550", 
                           colnames(out)[3], 
                           "Ramp1 SPR= .600",
                           "Ramp2 SPR= .600",
                           "SPR= .650", 
                           colnames(out)[4],
                           "Ramp1 SPR= .700",
                           "Ramp2 SPR= .700",
                           colnames(out)[-c(1:4)]),
             escape = FALSE)
```
\clearpage

```{r, results = 'asis'}
out = as.data.frame(round(reb[[1]]$acl_matrix[1:46, ],2))
out[,2] = round(reb[[2]]$acl_matrix[1:46, 2],2) #Set the SPR = 0.5 run to be from the no-ABC-cap run
colnames(out)[7] = "Yr= T\\textsubscript{MID}"

#Add SPR = 0.55 and SPR 0.65 runs
extra = as.data.frame(round(reb[[3]]$acl_matrix[1:46, ],2))
extra[,3] = round(reb[[4]]$acl_matrix[1:46, 3],2) #Set the SPR = 0.55 run to be from the no-ABC-cap run
out2 = as.data.frame(append(out, list("SPR= .550" = extra[,3]), after = 2))
out3 = as.data.frame(append(out2, list("SPR= .650" = extra[,5]), after = 4))

#Add ramp policies for SPR 0.6 and 0.7
ramp60 = as.data.frame(round(reb[[6]]$acl_matrix[1:46, ],2))
ramp70 = as.data.frame(round(reb[[5]]$acl_matrix[1:46, ],2))
out4 = as.data.frame(append(out3, list("Ramp1 SPR= .600" = ramp60[,4]), after = 4))
out5 = as.data.frame(append(out4, list("Ramp1 SPR= .700" = ramp70[,6]), after = 7))

#Add ramp policies for SPR 0.6 and 0.7 where catch was set to above the ABC
ramp602 = as.data.frame(round(reb[[8]]$acl_matrix[1:46, ],2))
ramp702 = as.data.frame(round(reb[[7]]$acl_matrix[1:46, ],2))
out6 = as.data.frame(append(out5, list("Ramp2 SPR= .600" = ramp602[,4]), after = 5))
out7 = as.data.frame(append(out6, list("Ramp2 SPR= .700" = ramp702[,6]), after = 9))

table_format(x = out7,
             caption = "Catches (mt) by year for rebuilding strategies, including ramp strategies. Catches in 2021-2022 for all strategies were set at values recommended by the Groundfish Management Team. Catches in 2023-2024 for the ramp strategies were fixed as described in the text.",
             label = "acl-mat",
             align = 'l',
             digits = 3,
             landscape = TRUE,
             col_names = c(colnames(out)[1:2], 
                           "SPR= .550", 
                           colnames(out)[3], 
                           "Ramp1 SPR= .600",
                           "Ramp2 SPR= .600",
                           "SPR= .650", 
                           colnames(out)[4],
                           "Ramp1 SPR= .700",
                           "Ramp2 SPR= .700",
                           colnames(out)[-c(1:4)]),
             escape = FALSE)
```
\clearpage

```{r, results = 'asis'}
out = as.data.frame(round(reb[[1]]$ofl_matrix[1:46, ],2))
out[,2] = round(reb[[2]]$ofl_matrix[1:46, 2],2) #Set the SPR = 0.5 run to be from the no-ABC-cap run
#Because ACLs no longer equal OFLs the OFLs for no-cap scenarios are less than acl's. Need to set values for the SPR = 0.5 run to be from the acl_matrix (with the exception of the first two fixed catch years).
out[-c(1,2),2] = round(reb[[2]]$acl_matrix[3:46, 2],2)
colnames(out)[7] = "Yr= T\\textsubscript{MID}"

#Add SPR = 0.55 and SPR 0.65 runs
extra = as.data.frame(round(reb[[3]]$ofl_matrix[1:46, ],2))
extra[,3] = round(reb[[4]]$ofl_matrix[1:46, 3],2) #Set the SPR = 0.55 run to be from the no-ABC-cap run
#Because ACLs no longer equal OFLs the OFLs for no-cap scenarios are less than acl's. However, the acl's do not reach the OFL levels as is the case for SPR = 0.5. Thus no need to set these to the acl_matrix like was done for SPR = 0.5
out2 = as.data.frame(append(out, list("SPR= .550" = extra[,3]), after = 2))
out3 = as.data.frame(append(out2, list("SPR= .650" = extra[,5]), after = 4))

#Add ramp policies for SPR 0.6 and 0.7
ramp60 = as.data.frame(round(reb[[6]]$ofl_matrix[1:46, ],2))
ramp70 = as.data.frame(round(reb[[5]]$ofl_matrix[1:46, ],2))
out4 = as.data.frame(append(out3, list("Ramp1 SPR= .600" = ramp60[,4]), after = 4))
out5 = as.data.frame(append(out4, list("Ramp1 SPR= .700" = ramp70[,6]), after = 7))

#Add ramp policies for SPR 0.6 and 0.7 where catch was set to above the ABC
ramp602 = as.data.frame(round(reb[[8]]$ofl_matrix[1:46, ],2))
ramp702 = as.data.frame(round(reb[[7]]$ofl_matrix[1:46, ],2))
out6 = as.data.frame(append(out5, list("Ramp2 SPR= .600" = ramp602[,4]), after = 5))
out7 = as.data.frame(append(out6, list("Ramp2 SPR= .700" = ramp702[,6]), after = 9))

#And need to divide ofls (which are actually the ABC) by the buffers (other than the SPR = 0.5 strategy, and first two years across runs)
#Cap buffers to the cat3 buffer
buffer <- PEPtools::get_buffer(2021:reb[[1]]$tmax,1,0.45)
buffer[which(buffer[,2]<0.778),2] = 0.778
out7[,-c(1:2)] = round(out7[,-c(1:2)]/buffer[,2],2)

table_format(x = out7,
             caption = "OFLs (mt) by year for rebuilding strategies, including ramp strategies.",
             label = "ofl-mat",
             align = 'l',
             digits = 3,
             landscape = TRUE,
             col_names = c(colnames(out)[1:2], 
                           "SPR= .550", 
                           colnames(out)[3], 
                           "Ramp1 SPR= .600",
                           "Ramp2 SPR= .600",
                           "SPR= .650", 
                           colnames(out)[4],
                           "Ramp1 SPR= .700",
                           "Ramp2 SPR= .700",
                           colnames(out)[-c(1:4)]),
             escape = FALSE)
```
\clearpage

```{r, results = 'asis'}
out = as.data.frame(round(reb[[1]]$relativeb_matrix[1:46, ],2))
out[,2] = round(reb[[2]]$relativeb_matrix[1:46, 2],2) #Set the SPR = 0.5 run to be from the no-ABC-cap run
colnames(out)[7] = "Yr= T\\textsubscript{MID}"

#Add SPR = 0.55 and SPR 0.65 runs
extra = as.data.frame(round(reb[[3]]$relativeb_matrix[1:46, ],2))
extra[,3] = round(reb[[4]]$relativeb_matrix[1:46, 3],2) #Set the SPR = 0.55 run to be from the no-ABC-cap run
out2 = as.data.frame(append(out, list("SPR= .550" = extra[,3]), after = 2))
out3 = as.data.frame(append(out2, list("SPR= .650" = extra[,5]), after = 4))

#Add ramp policies for SPR 0.6 and 0.7
ramp60 = as.data.frame(round(reb[[6]]$relativeb_matrix[1:46, ],2))
ramp70 = as.data.frame(round(reb[[5]]$relativeb_matrix[1:46, ],2))
out4 = as.data.frame(append(out3, list("Ramp1 SPR= .600" = ramp60[,4]), after = 4))
out5 = as.data.frame(append(out4, list("Ramp1 SPR= .700" = ramp70[,6]), after = 7))

#Add ramp policies for SPR 0.6 and 0.7 where catch was set to above the ABC
ramp602 = as.data.frame(round(reb[[8]]$relativeb_matrix[1:46, ],2))
ramp702 = as.data.frame(round(reb[[7]]$relativeb_matrix[1:46, ],2))
out6 = as.data.frame(append(out5, list("Ramp2 SPR= .600" = ramp602[,4]), after = 5))
out7 = as.data.frame(append(out6, list("Ramp2 SPR= .700" = ramp702[,6]), after = 9))


table_format(x = out7,
             caption = "Spawning output relative to the 40 percent of unfished spawning output target by year for rebuilding strategies, including ramp strategies.",
             label = "rel-ssb-mat",
             align = 'l',
             digits = 3,
             landscape = TRUE,
             col_names = c(colnames(out)[1:2], 
                           "SPR= .550", 
                           colnames(out)[3], 
                           "Ramp1 SPR= .600",
                           "Ramp2 SPR= .600",
                           "SPR= .650", 
                           colnames(out)[4],
                           "Ramp1 SPR= .700",
                           "Ramp2 SPR= .700",
                           colnames(out)[-c(1:4)]),
             escape = FALSE)
```
\clearpage
