\clearpage
# Figures

<!-- Main run figures -->
```{r, results = 'asis'}
add_figure(
filein = file.path(getwd(), "figures", "rebuilding_probability_forREPORT.png"), 
caption = "Probability of rebuilding by year for the base alternative rebuilding strategies",
label = 'prob-fig')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(getwd(), "figures", "rebuilding_acl_forREPORT.png"), 
caption = "Catches (mt) by year for the base alternative rebuilding strategies",
label = 'acl-fig')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(getwd(), "figures", "rebuilding_relative_sb_forREPORT.png"), 
caption = "Spawning output relative to the management target of 40 percent of unfished spawning output by year for the base alternative rebuilding strategies",
label = 'rel-ssb-fig')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(getwd(), "figures", "rebuilding_ssb_forREPORT.png"), 
caption = "Spawning output by year for the base alternative rebuilding strategies",
label = 'ssb-fig')
```


<!-- <!-- Runs with no abc max -->
<!-- ```{r, results = 'asis'} -->
<!-- add_figure( -->
<!-- filein = file.path(reb[[2]]$loc, "rebuilding_probability.png"),  -->
<!-- caption = "Probability of rebuilding by year for alternative rebuilding strategies when not constraining catches by the ABC", -->
<!-- label = 'prob-fig-noABCmax') -->
<!-- ``` -->

<!-- ```{r, results = 'asis'} -->
<!-- add_figure( -->
<!-- filein = file.path(reb[[2]]$loc, "rebuilding_acl.png"),  -->
<!-- caption = "Catches (mt) by year for alternative rebuilding strategies when not constraining catches by the ABC", -->
<!-- label = 'acl-fig-noABCmax') -->
<!-- ``` -->

<!-- ```{r, results = 'asis'} -->
<!-- add_figure( -->
<!-- filein = file.path(reb[[2]]$loc, "rebuilding_relative_sb.png"),  -->
<!-- caption = "Spawning output relative to the management target of 40 percent of unfished spawning output by year for alternative rebuilding strategies when not constraining catches by the ABC", -->
<!-- label = 'rel-ssb-fig-noABCmax') -->
<!-- ``` -->

<!-- ```{r, results = 'asis'} -->
<!-- add_figure( -->
<!-- filein = file.path(reb[[2]]$loc, "rebuilding_ssb.png"),  -->
<!-- caption = "Spawning output by year for alternative rebuilding strategies when not constraining catches by the ABC", -->
<!-- label = 'ssb-fig-noABCmax') -->
<!-- ``` -->


<!-- <!-- Runs based on SS model with sex = 1 -->
<!-- ```{r, results = 'asis'} -->
<!-- add_figure( -->
<!-- filein = file.path(reb[[3]]$loc, "rebuilding_probability.png"),  -->
<!-- caption = "Probability of rebuilding by year for alternative rebuilding strategies when based on an SS model with sex = 1", -->
<!-- label = 'prob-fig-sex1') -->
<!-- ``` -->

<!-- ```{r, results = 'asis'} -->
<!-- add_figure( -->
<!-- filein = file.path(reb[[3]]$loc, "rebuilding_acl.png"),  -->
<!-- caption = "Catches (mt) by year for alternative rebuilding strategies when based on an SS model with sex = 1", -->
<!-- label = 'acl-fig-sex1') -->
<!-- ``` -->

<!-- ```{r, results = 'asis'} -->
<!-- add_figure( -->
<!-- filein = file.path(reb[[3]]$loc, "rebuilding_relative_sb.png"),  -->
<!-- caption = "Spawning output relative to the management target of 40 percent of unfished spawning output by year for alternative rebuilding strategies when based on an SS model with sex = 1", -->
<!-- label = 'rel-ssb-fig-sex1') -->
<!-- ``` -->

<!-- ```{r, results = 'asis'} -->
<!-- add_figure( -->
<!-- filein = file.path(reb[[3]]$loc, "rebuilding_ssb.png"),  -->
<!-- caption = "Spawning output by year for alternative rebuilding strategies when based on an SS model with sex = 1", -->
<!-- label = 'ssb-fig-sex1') -->
<!-- ``` -->


<!-- Sensitivity run figures -->
<!-- Spawning output and status comparisons -->
```{r, results = 'asis'}
add_figure(
filein = file.path("C:/Users/Brian.Langseth/Desktop/ca/rebuilder/write_up/figures", "rebuilder_sensitivities_compare2_spawnbio_uncertainty.png"), 
caption = "Change in estimated spawning output for the adopted stock synthesis base model (base) and the stock synthesis sensitivity model (RecCom Block 2001). Shading indicates 95 percent confidence intervals around each scenario",
label = 'ssb-sens')

add_figure(
filein = file.path("C:/Users/Brian.Langseth/Desktop/ca/rebuilder/write_up/figures", "rebuilder_sensitivities_compare4_Bratio_uncertainty.png"), 
caption = "Change in estimated fraction of unfished for the adopted stock synthesis base model (base) and the stock synthesis sensitivity model that informs the rebuilding sensitivity (RecCom Block 2001). Shading indicates 95 percent confidence intervals around each scenario",
label = 'depl-sens')
```


```{r, results = 'asis'}
add_figure(
filein = file.path("C:/Users/Brian.Langseth/Desktop/ca/rebuilder/write_up/figures", "selex_compare.png"), 
caption = "Recreational and commercial selectivity for the stock synthesis sensitvity model with blocks in 2001 and allowing dome-shaped selectivity (red lines) compared to the selectivity for the adopted base model (blue lines)",
label = 'selex-sens')
```

<!-- Mean length fits -->
```{r, results = 'asis', echo = FALSE}
#Commercial
add_figure(
filein = file.path("C:/Users/Brian.Langseth/Desktop/ca", "9_0_0_postSSC_base", "plots", "comp_lenfit_data_weighting_TA1.8_CA_Commercial.png"), 
caption = "Mean length and fit (blue line) for the commercial length data from the adoped stock synthesis base model with 95 percent confidence intervals (solid black bar) based on current samples sizes. Thinner intervals (with capped ends) show result of further adjusting sample sizes based on suggested multiplier for Francis data weighting",
label = 'MeanLengthFit-com-base',
width = 90, height = 90)

add_figure(
filein = file.path(rebuild_dir, "9_4_0_recComBlock2001", "plots", "comp_lenfit_data_weighting_TA1.8_CA_Commercial.png"), 
caption = "Mean length and fit (blue line) for the commercial length data from the stock synthesis sensitivity model with 95 percent confidence intervals (solid black bar) based on current samples sizes. Thinner intervals (with capped ends) show result of further adjusting sample sizes based on suggested multiplier for Francis data weighting",
label = 'MeanLengthFit-com-sens',
width = 90, height = 90)

#Recreational
add_figure(
filein = file.path("C:/Users/Brian.Langseth/Desktop/ca", "9_0_0_postSSC_base", "plots", "comp_lenfit_data_weighting_TA1.8_CA_Recreational.png"), 
caption = "Mean length and fit (blue line) for the recreational length data from the adoped stock synthesis base model with 95 percent confidence intervals (solid black bar) based on current samples sizes. Thinner intervals (with capped ends) show result of further adjusting sample sizes based on suggested multiplier for Francis data weighting",
label = 'MeanLengthFit-rec-base',
width = 90, height = 90)

add_figure(
filein = file.path(rebuild_dir, "9_4_0_recComBlock2001", "plots", "comp_lenfit_data_weighting_TA1.8_CA_Recreational.png"), 
caption = "Mean length and fit (blue line) for the recreational length data from the stock synthesis sensitivity model with 95 percent confidence intervals (solid black bar) based on current samples sizes. Thinner intervals (with capped ends) show result of further adjusting sample sizes based on suggested multiplier for Francis data weighting",
label = 'MeanLengthFit-rec-sens',
width = 90, height = 90)
```

<!-- Person residuals -->
```{r, results = 'asis', echo = FALSE}
add_figure(
filein = file.path("C:/Users/Brian.Langseth/Desktop/ca", "9_0_0_postSSC_base", "plots", "comp_lenfit__multi-fleet_comparison.png"), 
caption = "Pearson residuals for the recreational and commercial fleets for the adopted stock synthesis base model. Closed bubbles are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'Pearson-base',
width = 90, height = 90)

add_figure(
filein = file.path(rebuild_dir, "9_4_0_recComBlock2001", "plots", "comp_lenfit__multi-fleet_comparison.png"), 
caption = "Pearson residuals for the recreational and commercial fleets for the stock synthesis sensitivity model. Closed bubbles are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'Pearson-sens',
width = 90, height = 90)
```

<!-- Aggregate length plots -->
```{r, results = 'asis', echo = FALSE}
add_figure(
filein = file.path("C:/Users/Brian.Langseth/Desktop/ca", "9_0_0_postSSC_base", "plots", "comp_lenfit__aggregated_across_time.png"), 
caption = "Aggregated length comps over all years for the adopted stock synthesis base model",
label = 'aggLenFit-base')

add_figure(
filein = file.path(rebuild_dir, "9_4_0_recComBlock2001", "plots", "comp_lenfit__aggregated_across_time.png"), 
caption = "Aggregated length comps over all years for the stock synthesis sensitivity model",
label = 'aggLenFit-sens')
```

\clearpage