\clearpage
### Figures

<!-- Main run figures -->
```{r, results = 'asis'}
add_figure(
filein = file.path(getwd(), "figures", "rebuilding_probability_forREPORT_ALT.png"), 
caption = "Probability of rebuilding by year for the alternative rebuilding strategies where assumed 2024 removals were set to 6.23 mt",
label = 'prob-fig-alt',
alt_caption = "Line plot of probability of recovery by year after 2021 showing 11 lines that represent each rebuilding strategy")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(getwd(), "figures", "rebuilding_acl_forREPORT_ALT.png"), 
caption = "Catches (mt) by year, starting in 2025, for the alternative rebuilding strategies where assumed 2024 removals were set to 6.23 mt",
label = 'acl-fig-alt',
alt_caption = "Line plot of catches by year after 2024 showing 11 lines that represent each rebuilding strategy")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(getwd(), "figures", "rebuilding_relative_sb_forREPORT_ALT.png"), 
caption = "Spawning output relative to the management target of 40 percent of unfished spawning output by year, starting in 2025, for the alternative rebuilding strategies where assumed 2024 removals were set to 6.23 mt",
label = 'rel-ssb-fig-alt',
alt_caption = "Line plot of relative spawning output by year after 2024 showing 11 lines that represent each rebuilding strategy")
```

```{r, results = 'asis'}
add_figure(
filein = file.path(getwd(), "figures", "rebuilding_ssb_forREPORT_ALT.png"), 
caption = "Spawning output by year, starting in 2025, for the alternative rebuilding strategies where assumed 2024 removals were set to 6.23 mt",
label = 'ssb-fig-alt',
alt_caption = "Line plot of spawning output by year after 2024 showing 13 lines that represent each rebuilding strategy")
```

\clearpage