## Fishery-Dependent Data

### Commercial Fishery

#### Landings

Commercial landings of `r spp` in `r state` were provided directly by the WDFW for years ranging from 1889 to 2014 and compiled from PacFIN for years from 2015 to 2020. Only eight of the years before 1973 have non-zero landings, and all are less than 0.04 mt. Consequently, we exclude landings before 1973 for this assessment. There is limited commercial fishery removals of `r spp` off the `r state` coast and not all years have commercial landings. The highest annual landing was 2.20 mt in 1973 with only three other years exceeding 1 mt of harvest (1989, 1990, and 2000). `r state` closed state waters to commercial fixed gears in 1995 and to trawling in 1999. `r Spp` are occasionally encountered as bycatch in commercial fisheries outside of state waters and are harvested by four treaty tribes off the `r state` coast that fish under separate commercial rules and are not subject to the state water closures. `r Spp` is landed as part of the mixed nearshore rockfish market category and species composition data are applied. In 2020, access to Neah Bay was closed for commercial fisheries sampling due to the COVID-19 pandemic, so an average proportion for `r spp` composition data taken from 2017-2019 was applied to the nearshore rockfish market category for the Neah Bay Port group in 2020.

The input catches in the model represent total removals: landings plus discards (Table \ref{tab:allcatches} and Figure \ref{fig:catch}). Discard totals for the commercial fleet for years between 2002-2019 were determined based on WCGOP data provided in the Groundfish Expanded Mortality Multiyear (GEMM) product. The total coastwide observed discards were allocated by state and area based on the total observed landings observed by WCGOP. Discards were added to landings in years where landings were non-zero to obtain total removals for 2002-2019. Total removals prior to 2002, and for 2020 where no WCGOP data were yet available, were calculated using the average discard rates from WCGOP for years within both landings and discards for `r state` (8.3 percent).

#### Length Compositions 

Available length data collected from commercial fisheries from 1980-2019 were extracted from PacFIN for `r state` `r spp` (Table \ref{tab:com-len-samps}, extracted 2/23/2021). No commercial length samples were collected in 2020 due to sampling restrictions caused by the COVID-19 pandemic. There are very few length samples of `r spp` from commercial fisheries in `r state`. The largest number of length samples (n = 106) occurs for 2006, while every other year had fewer than 20 samples.

The distribution of the lengths in the commercial data was variable and ranged between 20 - 50 cm (the maximum length data bin size, Figure \ref{fig:com-len-data}). Given the high number of samples in 2006 compared to other years, the aggregate lengths were very similar to the length data for 2006 (Figure \ref{fig:wa-len-agg}). The mean size observed by the commercial fishery was variable within and across years (Figure \ref{fig:mean-com-len-data}). 

The input sample sizes for the commercial length data were calculated via the Stewart method (Ian Stewart, personal communication) which incorporate the number of trips and fish by year:

\begin{centering}

Input effN = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $<$ 44

Input effN = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $\geq$ 44

\end{centering}

Despite the variability in commercial lengths due to small sample size, the model was able to estimate selectivity for the commercial fleet. A sensitivity analysis was conducted by setting the selectivity of the commercial fleet to mirror that of the recreational fleet (see Section \ref{sensitivity-analyses} for details). 

### Recreational / Sport Fishery

#### Landings

Recreational removals are the primary source of fishing mortality for `r spp` (Table \ref{tab:allcatches} and Figure \ref{fig:catch}). Removals were specified in numbers of fish (1,000s) and were converted to metric tons internally to the model (Table \ref{tab:nums-mt}). Annual retained catch (in numbers) from the Washington recreational fishery in 1967 and from 1975 to 1990 were provided from WDFW published historical information. Retained catch for years between 1967 and 1975 were calculated based on a linear interpolation for missing data. The linear interpolation between 1967 to 1975 was extended back in time to determine the first year of positive catch for the recreational fleet, which was 1958. Recreational data from 1990 through 2020 are from WDFW’s Ocean Sampling Program (OSP) and the Puget Sound baseline (PSB) sampling program. Catches within Puget Sound were not included in the model, but the PSB encounters anglers fishing in the ocean and return to ports. Discard estimates are available from 2002 through 2020 from the OSP and PSB program. Prior to 2002 discard estimates are based on a linear regression of discard to retained catch. Throughout the time series a discard mortality rate was applied by harvest depth if information was available. An overall discard mortality of 31% was applied to `r spp` if harvest depth was unknown. Mortality rates by depth have been reviewed and approved by the PFMC Science and Statistical Committee. The sum of retained and dead released `r spp` made up the total removal (in numbers) from the recreational fishery. The recreational removals generally increased over-time, spiked in 1990 to an all time high of over 5,600 fish, generally declined to 2010, with catches between 1,000 and 2,000 fish per year through 2020, with the exception of 2019, when over 2,700 fish were removed.

#### Length Compositions 

Length compositions for the recreational fleet are available from 1981, 1982, 1983, 1987, and then for each year from 1995 - 2020 (Table \ref{tab:len-samps}). Sample sizes were minimal in years before 1995. The distribution of lengths of `r spp` observed by the recreational fleet ranged between 20 and 50 cm (the maximum length data bin size, Figure \ref{fig:rec-len-data}). The mean length observed by year had limited variation since 1995 ranging between 35 - 40 cm, increasing slightly over time (Figure \ref{fig:mean-rec-len-data}). Mean length in years prior to 1995, which had small sample sizes, was highly variable. 

The input sample sizes for the recreational length data were set equal to the number of length samples available by year. 

