## Fishery-Independent Data

No fishery-independent data sources that are commonly incorporated in West Coast groundfish assessments (as required by the data moderate Terms of Reference) had adequate sample size of `r spp` off the `r state` coast to include abundance indices for this assessment. The WCGBTS and the Triennial survey collected data off the `r state` coast on rockfish biology and abundance. There were no more than ten positive tows of `r spp` in any one year coastwide in the WCGBTS, but typically fewer than five. Similarly there were no more than five positive tows of `r spp` in any one year coastwide for the Triennial survey. Given that indices of abundance were not calculated due to small sample sizes, length composition data from the WCGBTS (n = 91) and Triennial Survey (n = 42) off `r state` were not included in the model. Biological data from the WCGBTS survey were used in external calculations of biological parameters, including growth and weight-at-length relationships. No ages or weights for `r spp` were available from the Triennial survey.

Length data from the International Pacific Halibut Commission longline survey (N = 38), the Marine Fish Science longline survey (N = 36), and the Marine Fish Science rod and reel survey (N = 38) were provided by the WDFW. Lengths ranged from 28 - 45 cm from the longline surveys and 19 - 37 cm from the rod and reel survey. These data were not included in the model nor used in external calculations of biological parameters. 