<!-- Base Model Results -->

```{r, echo=FALSE, results='asis'}
general_wd = "U:/Stock assessments/quillback_rockfish_2021/write_up/general_text"
filein = file.path(general_wd, '33_results_basemodel.Rmd')
read_child(filein)
```

### Parameter Estimates

Estimated parameter values are provided in Table \ref{tab:params}. The ln($R_0$) was estimated at `r round(model$parameters[model$parameters$Label == 'SR_LN(R0)', 'Value'], 3)`. The selectivity curves for the commercial and recreational fleet are shown in Figure \ref{fig:selex}. Selectivity was fixed to be asymptotic with a peak in maximum selectivity for the commercial fleet starting at `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_WA_Commercial(2)', 'Value'], 1)` cm and a peak in maximum selectivity for the recreational fleet starting at `r round(model$parameters[model$parameters$Label == 'Size_DblN_peak_WA_Recreational(1)', 'Value'], 1)`. Sensitivities to the selectivity shape and potential exclusion of sparse years of length data for both the commercial and recreational fleets were explored (see below in the [Sensitivity Analyses](#sensitivity-analyses) section). 

### Fits to the Data

Fits to the length data are shown based on the Pearson residuals-at-length, the annual mean lengths, and aggregated length composition data for the commercial and recreational fleets. Fits to the length composition data by year are provided in [Appendix A](#append_a). 

The Pearson residuals for the commercial fishery are generally uninformative given the sparseness of the commercial length data (Figure \ref{fig:com-pearson}). Input sample size was largest in 2006, and then in 2014 and 2019, and the model fit length data in these years relatively well (see [Appendix A](#append_a) for details). The mean lengths observed by the commercial fishery are highly variable by year however mean length in the most well sampled years (2006, 2014, and 2019) are well fit (Figure \ref{fig:com-mean-len-fit}). A sensitivity fixing the selectivity of the commercial fleet to mirror that of the recreational selectivity was performed and presented in the [Sensitivity Analyses](#sensitivity-analyses) section below.

The Pearson residuals for the recreational fishery show a pattern of greater observations that start around 1995 and appear to move through the length data by year, possibly indicating a strong or multiple strong recruitments entering the population (Figure \ref{fig:rec-pearson}). The base model was not allowed to estimate annual recruitment deviations due to data informing recruitment deviations being generally uninformative. The assessment of `r spp` off the Oregon coast, which did include annual recruitment deviations, estimated strong recruitments in 1993 and 1995 indicating that oceanographic forces that drive recruitment success or failure may be shared across Oregon and Washington. However, the length data for `r state` suggest little recruitment over the last two decades, contrary to the `r spp` assessment off the Oregon coast. The mean lengths across years starting in 1995 show increasing size in the population ranging roughly between 33 to 40 cm by year that the model overfits in the early years and underfits in recent years (Figure \ref{fig:rec-mean-len-fit}). 

Aggregate fits by fleet are shown in Figure \ref{fig:agg-len-fit}. There are a few things that stand out when examining the aggregated length composition data. First, the estimated fits to the data match the general shape of the aggregated lengths as well as the observed ranges of lengths. Both fleets show a similar aggregated peak around 40 cm, yet the recreational fleet shows proportionally more smaller fish than the commercial fleet. Second, the model expects a higher proportion of the largest fish relative to the data. This may indicate that the true selectivity of the recreational fleet may have some level of reduced selectivity for the largest fish (dome-shaped). Sensitivities examining dome-shaped selectivity and estimating annual recruitment deviations were performed and presented in the [Sensitivity Analyses](#sensitivity-analyses) section below.

### Population Trajectory

The predicted spawning output (in millions of eggs) is given in Table \ref{tab:timeseries} and plotted in Figure \ref{fig:ssb}. The estimates of spawning output across time are uncertain with the base model estimating a spawning output of `r round(model$derived_quants[model$derived_quants$Label == 'SSB_2021','Value'], 2)` in `r endyr+1` with a 95 percent asymptotic confidence interval ranging from `r paste(round(sb_low,2), "-", round(sb_high,2))` millions of eggs. The predicted spawning output from the base model generally showed a steady decline over the early part of the time series with the spawning output stabilizing around 2010 and increasing in recent years. The total biomass shows a similar slow decline and then recent increase across the modeled years (Figure \ref{fig:tot-bio}).

The `r endyr+1` spawning output relative to unfished equilibrium spawning output is just under the target of 40 percent of unfished spawning output (`r round(model$derived_quants[model$derived_quants$Label == 'Bratio_2021','Value'], 2)`, Figure \ref{fig:depl}). Approximate 95% confidence interval based on the asymptotic variance estimates show that the uncertainty in the estimated spawning output is large ranging between approximately 10 - 70 percent of unfished equilibrium spawning output.

The stock-recruit curve resulting from a value of steepness fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"],2)` is shown in Figure \ref{fig:bh-curve}. The estimated annual recruitment is shown in Figure \ref{fig:recruits}.

