## Model Diagnostics

### Convergence

Proper convergence was determined by starting the minimization process from dispersed values of the maximum likelihood estimates and adjusting phases of the estimated parameters to determine if the model found a better minimum. Starting parameters were jittered by 10 percent. This was repeated 100 times with 19 out of 100 runs returning to the base model negative log-likelihood. A lower negative log-likelihood model fit was not found and all runs converged. Alternative phasing was done over three models by setting phases of all parameters other than $R_0$ to 2, setting selectivity parameters for the recreational fleet to phase 4, and setting selectivity parameters for the commercial fleet to phase 4. No model with lower negative log-likelihood was found through alternative phasing. Through the jittering done as explained, likelihood profiles (described below), and alternative phasing, we are confident that the base model as presented represents the best fit to the data given the assumptions made. There were no difficulties in inverting the Hessian to obtain estimates of variability throughout initial model attempts and all explorations resulted in a positive-definite Hessian. 

### Likelihood Profiles

Likelihood profiles were conducted for $R_0$, steepness, natural mortality, $L_{\infty}$, growth coefficient ($k$), CV at maximum length, and the peak in selectivity for the recreational fleet separately. These likelihood profiles were conducted by fixing the parameter at specific values and estimating the remaining parameters based on the fixed parameter value. Two additional profiles on steepness and CV at maximum length were done while fixing the recreational selectivity parameters.  

In regards to values of ln($R_0$), values from approximately 1.8 to 4.0 were supported with the negative log-likelihood minimized at the value from the base model of `r round(log(model$derived_quants[model$derived_quants$Label == "Recr_Virgin",2]),3)` (Figure \ref{fig:r0-profile}). This suggests the data contain information about the minimum scale of the population, but limited information on how large the population could be. Increasing ln($R_0$) relative to the base model resulted in an increase in stock scale (Figure \ref{fig:r0-ssb}) and status (Figure \ref{fig:r0-depl}). 

Similar to results for $R_0$, the profile on steepness suggests the data have limited information on the value of steepness. Values of steepness between 0.3-1.0 were supported based on change in negative log-likelihood, with the lowest negative log-likelihood occurring near a value of 1.0, which is greater than the value of steepness in the base model of `r round(model$parameters[model$parameters$Label == "SR_BH_steep",3],2)` (Figure \ref{fig:h-profile}). Assuming lower steepness values resulted in higher estimates of unfished and recent spawning output, particularly for the lowest steepness values (0.3 and 0.4; Figure \ref{fig:h-ssb}), and similar levels of depletion relative to unfished conditions, with the exception of the lower values (0.3 and 0.4; Figure \ref{fig:h-depl}). We explored the reason for different dynamics at low steepness values. As opposed to having convergence issues, we found the models converged on estimates of peak selectivity for the recreational fleet near 33 cm and estimates of ln($R_0$) near 3.0, which are greatly different than the base model estimates. The steepness profile therefore highlights the high uncertainty in the base model around peak selectivity and ln($R_0$) estimates. We further explored the effect of selectivity on the profile for steepness by profiling across steepness values while fixing recreational selectivity to base model estimates. Fixing commercial selectivity had no effect. The resulting profile suggests the likelihood surface is flat across steepness values and the negative log-likelihood is minimized near steepness values of 1.0 (Figure \ref{fig:h-recfix-profile}). Low steepness values resulted in higher unfished spawning output (Figure \ref{fig:h-recfix-ssb}), and without the effect of changes in selectivity greater depletion compared to the base model (Figure \ref{fig:h-recfix-depl}). 

Given that estimates of peak selectivity are uncertain in the base model, and selectivity estimates can influence parameter estimates, as was shown for steepness, we profiled across values of peak selectivity for the recreational fleet (Figure \ref{fig:recselex-profile}). The profile on peak selectivity supported all estimates of peak selectivity but the minimum of the negative log-likelihood was found at the base model estimate of `r round(model$parameters[model$parameters$Label == "Size_DblN_peak_WA_Recreational(1)",3],2)`. Lower estimates of peak selectivity resulted in greater estimates of unfished and recent spawning output (Figure \ref{fig:recselex-ssb}) as well as higher estimates of stock status (Figure \ref{fig:recselex-depl}).

The negative log-likelihood profile across natural mortality supported the largest value in the profile. The estimated stock trajectories assuming lower or higher natural mortality values affected the estimated unfished spawning output (Figures \ref{fig:m-ssb}), and resulted in stock statuses near to or above the management target (Figures \ref{fig:m-depl}). Low values of $M$ resulted in similar results to low values of steepness, with estimates of peak selectivity near 32 cm, however estimates of ln($R_0$) were nearer the estimate from the base model. For values of $M$ above 0.1, the estimate for peak selectivity of the recreational fleet was reaching its bound.   

A profile across a range of $L_{\infty}$ values was also conducted and values from approximately 40 to 44 cm were supported with a minimum negative log-likelihood around 41 cm (Figure \ref{fig:linf-profile}). The value of $L_{\infty}$ in the model was fixed at `r model$parameters[model$parameters$Label == "L_at_Amax_Fem_GP_1","Value"]`. The stock scale and status is variable across alternative $L_{\infty}$ values where assuming lower values resulted in large increases in unfished and recent spawning output (Figure \ref{fig:linf-ssb}) and stock status (Figure \ref{fig:linf-depl}).

The negative log-likelihood profile across values of $k$ supported all values within the profile but was minimized at lower values of $k$ (Figure \ref{fig:k-profile}). The value of $k$ in the base model was fixed at `r model$parameters[model$parameters$Label == "VonBert_K_Fem_GP_1","Value"]`. Lowering the value of $k$ resulted in higher estimates of unfished and recent spawning output (Figure \ref{fig:k-ssb}) and stock status (Figure \ref{fig:k-depl}).

Values between 0.06 and 0.09 for the CV at maximum length were supported by the negative log-likelihood profile, with a minimum at 0.07 (Figure \ref{fig:cv2-profile}). For values of CV at maximum length less than the value assumed in the base model of `r model$parameters[model$parameters$Label == "CV_old_Fem_GP_1","Value"]`, spawning output (Figure \ref{fig:cv2-ssb}) and stock status (Figure \ref{fig:cv2-depl}) differed greatly from for the base model. As was the case for low values of steepness, this occurred because the models converged on estimates of peak selectivity for the recreational fleet near 33 cm and estimates of ln($R_0$) near 3.5. Therefore, as was done for steepness, we also profiled across CV at maximum length while fixing recreational selectivity to base model estimates. The resulting profile was minimized at a value of 0.08, and supported values between 0.07-0.1 (Figure \ref{fig:cv2-recfix-profile}). Lower values for CV at maximum length resulted in higher stock scale (Figure \ref{fig:cv2-recfix-ssb}) and stock status (Figure \ref{fig:cv2-recfix-depl}) compared to the base model.


### Retrospective Analysis

A five-year retrospective analysis was conducted by running the model using data up to 2015, 2016, 2017, 2018, and 2019. The estimated spawning output was consistent with the base model when the last three years of data were removed (Figures \ref{fig:retro-ssb} and \ref{fig:retro-depl}). Removing 4 and 5 years of data resulted in a downward shift in stock scale and status. 

### Sensitivity Analyses

A number of sensitivity analyses were conducted. Sensitivities were generally conducted as a single exploration from the base model assumptions and/or data, and were not performed in a cumulative fashion. Exceptions include reweighting the length composition data when estimating recruitment deviations, and including annual recruitment deviations when estimating dome-shaped selectivity for the recreational fleet. 

\begin{enumerate}
   
  \item Estimate annual recruitment deviations.
  
  \item Estimate annual recruitment deviations and update the data weighting values.

  \item Data weighting according to the McAllister-Ianelli method (MI DW) using the weighting values shown in Table \ref{tab:dw}. 
  
  \item Data weighting according to the Dirichlet Multinomial method (DM DW) where the estimated parameters are shown in Table \ref{tab:dw}. 

  \item Estimate $L_{\infty}$.

  \item Estimate the coefficient of variation in length of older fishes.

  \item Estimate natural mortality ($M$).
  
  \item Exclude composition data prior to 1995 for the recreational fleet.
  
  \item Set the selectivity of the commercial fleet to mirror that of the recreational fleet.
  
  \item Allow recreational selectivity form to be dome-shaped while also estimating annual recruitment deviations. 
  
  \item Allow commercial selectivity form to be dome-shaped.

  \item Estimate a recreational selectivity block from 1958-1999, and 2000-2020.   
  
  \item Include model found during alternate phasing explorations. This model had very similar (but poorer) negative log-likelihood value to that of base model but different stock scale.
  
\end{enumerate}

Sensitivity runs estimating $k$ and estimating a dome-shaped selectivity form for the recreational fishery were also conducted but resulted in the model failing to estimate a reasonable biomass scale (near the upper bound of ln($R_0$) of 20). 

Likelihood values and estimates of key parameters from each sensitivity are available in Table \ref{tab:sensitivities}. Plots of the estimated time-series of spawning output and relative spawning output are shown in Figures \ref{fig:sens-ssb} and \ref{fig:sens-depl}. There was high uncertainty in estimates of $R_0$ for the sensitivities estimating $L_{\infty}$ and the coefficient of variation in length of older fishes and therefore plots were made without these two sensitivities and are shown in Figures \ref{fig:sens-ssb-subset} and \ref{fig:sens-depl-subset}.

The three sensitivities that had the largest impact relative to the base model were the ones that estimated $L_{\infty}$, the coefficient of variation in length of older fishes, and the model observed while exploring alternative phases (Figures \ref{fig:sens-ssb} and \ref{fig:sens-depl}). These sensitivities estimated ln($R_0$) between 50 and 75 percent larger than the base model despite estimating a change in $L_{\infty}$ of 2 cm (from `r model$parameters[model$parameters$Label == "L_at_Amax_Fem_GP_1","Value"]`), change in the coefficient of variation in length of older fishes to around 7 percent (from 10 percent), and changing the phase for estimating commercial selectivity to be after the phase for estimating recreational selectivity. The alternative phasing model was also observed for the vast majority of the jitter runs that did not obtained the minimum negative log-likelihood, which was 0.2 units larger than the base model negative log-likelihood. 

The next two sensitivities that had the largest impact on stock scale relative to the base model were the sensitivities exploring data weighting using the DM Method and the sensitivity estimating natural mortality. Using the DM method for data weighting resulted in a larger estimate of unfished and recent spawning output than the base model, and estimating natural mortality resulted in a smaller estimate of unfished and recent spawning output than the base model (Figures \ref{fig:sens-ssb-subset} and \ref{fig:sens-depl-subset}). Both sensitivities resulted in higher stock status than the base model. Estimating natural mortality resulted in a tradeoff with selectivity. When allowing flexibility in $M$, the model estimated a higher value than the base model, resulting in higher estimates for the peak size in selectivity for both fleets. The estimate of $M$ is therefore limited by the bounds for the parameter estimates for peak selectivity. 

The sensitivity estimating annual recruitment deviations resulted in a lower biomass scale, and level of depletion such that spawning output in `r endyr+1` was below the threshold of 25 percent of unfished spawning output (Figures \ref{fig:sens-ssb-subset} and \ref{fig:sens-depl-subset}). This applied whether data weighting values were updated or not. The estimates or recruitment deviations had a period of above-average recruitment from 1987 to 2003, then switched to a period of below-average recruitment (Figure \ref{fig:sens-recdev}). The recruitment deviation estimates were likely being driven by smaller lengths observed in the recreational fleet in the mid 1990s, as well as a lack of smaller fish being caught since 2000 (Figure \ref{fig:mean-rec-len-data}). Furthermore, the variability of the recruitment deviations prior to 2004 were higher than the assumed variability in recruitment (0.6), suggesting the increased recruitments were not well informed by the data. When adding recruitment deviations and updating data weighting values, individual years of positive recruitment deviations were more apparent, particularly for 1990, 1994, and 2000, and had uncertainty less than that of sigmaR. Lastly, estimating recruitment resulted in higher estimates of peak selectivity for both the recreational and commercial, well above the average maximum size in the population. The general pattern of recruitment deviations estimated seemed extreme for the `r state` model, but showed some coherence with the recruitment deviations estimated in the separate Oregon model. The Oregon base model estimated above average recruitment in the late 1990s which led to an increase in spawning output during the 2000s. This may potentially suggest that `r spp` off the coast of Oregon and Washington experience similar drivers in recruitment, however, the Oregon model estimated periods of higher recruitment since 2000 to fit pulses of small fish in the length data and support increasing catches over time, whereas the `r state` base model estimates lower than average recruitment throughout that time period.  

### Length-Based Estimate of Depletion 

An exploratory length-based analysis was done using a Stock Synthesis Length-Only model (SS-LO; [@cope_implementing_2013]) to produce an independent estimate of selectivity and depletion based on observed recreational lengths from 1995-2020. SS-LO is a length only version of Stock Synthesis, meaning the removal history is removed, but the same life history values and length compositions are used. The underlying assumption is that the population has gone through an aggregate constant catch and constant recruitment period in order to get an estimate of the current stock status. Length compositions are fit by estimating parameters ln($R_0$) (a nuisance parameter because it does not matter the value, but allows for best fits to the length compositions) and the selectivity by fleet. All other model specifications (e.g. sex-specific life history) match the reference model. This analysis indicated that `r spp` were 50 percent selected near 35 cm with full selection at 45 cm. The estimate of depletion for 2021 was 0.57. This type of analysis can provide insight on the fishing effort based on life history and observed length data in the absence of an integrated assessment model. The estimate of the depletion was used to provide an external estimate of stock status for use within a Simple Stock Synthesis run as described below.

### Simple stock synthesis

A Simple Stock Synthesis (SSS) was run to compare the results from the base model with a simpler modeling approach. SSS samples via Monte Carlo from five key parameter distributions: natural mortality, steepness, length at maximum size, the von Bertalanffy growth coefficient, and stock status in a specific year. The parameterization of the priors assumed in the base model were used to create sampling distributions for natural mortality, steepness, length at maximum size, and the growth coefficient. Selectivity was assumed to be as estimated from SS-LO. Two alternative assumptions regarding the distribution of current stock status were explored, one from the base model and the other from SS-LO. SSS applies parameter draws from each of the five parameters within the model and then estimates an $R_0$ value based on the fixed removals and drawn parameters. 

\begin{enumerate}

	\item Current stock status based on the estimate from the base model (SS-CL):
	\begin{itemize}
		\item Number of draws = 1000,
		\item $M$ = log-normal distribution ($\mu$ = 0.057, $\sigma$ = 0.20),
		\item $h$ = truncated beta ($\alpha$ = 0.72, $\beta$ = 0.15, a = 0.20, b = 1.0),
		\item $L_{\infty}$ = normal distribution ($\mu$ = 43.04, $\sigma$ = 4.3),
		\item $k$ = normal distribution ($\mu$ = 0.199, $\sigma$ = 0.02), and
		\item Fraction unfished in `r endyr+1` = beta($\alpha$ = 0.40, $\beta$ = 0.20)
	\end{itemize}
	\item Current stock status based on estimate from the length-only model (SS-LO):
	\begin{itemize}
		\item Number of draws = 1000,
		\item $M$ = log-normal distribution ($\mu$ = 0.057, $\sigma$ = 0.20),
		\item $h$ = truncated beta ($\alpha$ = 0.72, $\beta$ = 0.15, a = 0.20, b = 1.0),
		\item $L_{\infty}$ = normal distribution ($\mu$ = 43.04, $\sigma$ = 4.3),
		\item $k$ = normal distribution ($\mu$ = 0.199, $\sigma$ = 0.02), and
		\item Fraction unfished in `r endyr+1` = beta($\alpha$ = 0.57, $\beta$ = 0.20)
	\end{itemize}
	
\end{enumerate}

The median of unfished spawning output, spawning output in `r endyr+1`, fraction unfished in `r endyr+1`, the OFL in `r endyr + 3`, and the Acceptable Biological Catch (ABC) in `r endyr + 3` based on the `r endyr +1` fraction unfished of 57 percent is shown in Table \ref{tab:SSS-57}. The prior distribution for parameters and the derived quantities with 95 percent uncertainty are shown in Figures \ref{fig:sss-prior-57} and \ref{fig:sss-quant-57}. Assuming that the stock was less depleted relative to the base model resulted in higher estimates of the OFL and ABC in 2023.

The median of unfished spawning output, spawning output in `r endyr+1`, fraction unfished in `r endyr+1`, the OFL in `r endyr + 3`, and the ABC in `r endyr + 3` based on the `r endyr +1` fraction unfished of 40 percent is shown in Table \ref{tab:SSS-40}. The prior distribution for parameters and the derived quantities with 95 percent uncertainty are shown in Figures \ref{fig:sss-prior-40} and \ref{fig:sss-quant-40}. Assuming that the stock was similarly depleted relative to the base model resulted in a slightly lower estimate of the OFL in 2023, and lower estimate of the ABC due to the application of the buffer applied in the SSS model as opposed to the constant catch appied in the base model. This confirms SSS results in similar estimates to the base model under comparable assumptions about depletion. 

### Unresolved Problems and Major Uncertainties

The primary uncertainty for the `r state` `r spp` model is in the scale of the population. The trajectory of the population is generally consistent across profiles and sensitivities however the scale of the population is poorly informed by data. This is evident in the relatively wide uncertainty in the estimate of ln($R_0$), as well as uncertainty in the estimate of the peak of the selectivity curve, leading to uncertainty around spawning biomass and around stock status. Estimating growth parameters, notably $L_{\infty}$ and the coefficient of variation in length of older fish affected the population scale greatly. Estimating recruitment deviations reduced the scale of the population, and also resulted in spawning output relative to unfished equilibrium spawning output falling below the threshold value. Profiles across the fixed parameters in the base model show support for wide range of values based on similar values of negative log-likelihood and also result in large changes in stock size and status. In particular, profiling across steepness, as well as across natural mortality values revealed that assuming low values for these parameters shifted the peak of selectivity to lower sizes and higher estimates of equilibrium recruitment, resulting in high spawning biomass and less depletion. These conditions were also found during jittering and when applying alternative phases, but those models were not the best fit to the data.

An additional uncertainty is whether the perceived lack of small fish in the recreational fishery is due to recruitment, sampling issues, or steady and ongoing changes in the fishery. An increase in smaller fish in 2020 may indicate a recruitment event, or perhaps changes in sampling practices, however more years of data would be needed to confirm this. `r Spp` are not targeted by the commercial and recreational fleets and so discarding of small fish may occur. Lengths in the rod and reel survey provided by WDFW were all from fish smaller than the peak in selectivity, but did not represent fish specifically discarded. Without knowledge of discarded lengths, we assumed no difference in length between discards and retained fish, and may be missing the catch and discards of smaller fish within the length compositions.  

