# Management 

## Reference Points

Reference points were calculated using the estimated selectivity and catch distributions among fleets in the most recent year of the model (`r endyr`, Table \ref{tab:referenceES}). Sustainable total yields  were `r round(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $SPR_{50\%}$ reference harvest rate. The spawning output equivalent to 40 percent of the unfished spawning output ($SB_{40\%}$) was `r round(model$derived_quants[model$derived_quants$Label == 'SSB_SPR', 'Value'], 2)` millions of eggs. 

The `r endyr+1` spawning output relative to unfished equilibrium spawning output is below the target of 40 percent but above the threshold of 25 percent of unfished spawning output in 2020 (`r 100*round(model$derived_quants[model$derived_quants$Label == 'Bratio_2021','Value'], 2)` percent, Figure \ref{fig:depl}). The fishing intensity, $1-SPR$, was above the harvest rate limit ($SPR_{50\%}$) from 1987 - 2012, and has been both above and below the harvest rate limit in recent years (Table \ref{tab:timeseries} and Figure \ref{fig:1-spr}). Figure \ref{fig:phase-plot} shows the phase plot of relative spawning output and fishing intensity. Table \ref{tab:referenceES} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield} shows the equilibrium yield curve based on a steepness value fixed at `r model$parameters[model$parameters$Label == "SR_BH_steep","Value"]`.


## Harvest Projections and Decision Tables

A ten year projection of the base model was estimated for years 2023-2032, with catches equal to the estimated yield at $SPR_{50\%}$ multiplied by buffer (0.778) based on a category 3 sigma and P* = 0.45 (Table \ref{tab:project}). The removals in 2021 and 2022 were set based on the mortality estimates from the GEMM product for the recreational fleet, averaged from 2018-2020, as requested by the PFMC Groundfish Management Team (GMT, personal communication). Removals in 2021 and 2022 were apportioned to recreational and commercial catches based on the average proportion from 2018-2020 that each fleet contributed to the total catch. The same apportionment was also applied to the constant catch values during the projection years (2023-3032).

Recreational catches were provided in numbers, so the internally estimated catch in weight from the model was used to calculate the average catch from 2018-2020. Projected catches in biomass for the recreational fleet were converted to catch in numbers based on iteratively searching for the catch in numbers that achieves the desired catch value (in biomass) for the recreational fleet, and is the reason the catches in biomass by year do not exactly equal the fixed catch value.        


<!-- Evaluation of Scientific Uncertainty -->

```{r, echo=FALSE, results='asis'}
filein = file.path(general_wd,'4_management_uncertainty.Rmd')
read_child(filein)
```

# Research and Data Needs

The ability to estimate additional process and biological parameters for `r spp` was limited by data.  Collecting the following data would be beneficial to future assessments of the stock:

\begin{itemize}

	\item Continue collecting length and otolith samples from recreational catches and collect length samples from recreational discards. This would ensured collected samples are not missing small fish if they are caught and retained and not missing small fish if they are caught and discarded. Lengths of discarded fish would allow estimating a separate discard fleet within the model.   

	\item Continue to collect length data for the commercial fleet if catches occur.
	
	\item Recruitment patterns showed lower than average recruitment in the 2000s. Additional data to support such patterns in recruitment would provide additional support for model estimates.  

\end{itemize}