## Summary of Management History and Performance

`r Spp` is managed by the Pacific Fishery Management Council (PFMC) as a part of the Nearshore Rockfish North and Nearshore Rockfish South complexes. The North and South complexes are split at N. 40$^\circ$ 10' Lat. N. off the U.S. West Coast. Each complex is managed based on a complex-level overfishing limit (OFL) and annual catch limit (ACL). The OFL and ACL values for the complexes are determined by summing the species specific OFLs and ACLs managed within each complex. Removals for species within each Nearshore complex are managed and tracked against the complex total OFL and ACL, rather than on a species by species basis.

`r Spp` was most recently assessed in 2010 using Depletion-Based Stock Reduction Analysis (DB-SRA) to provide estimates of coastwide OFLs ([@DickandMacCall_dbsra_2010]). The coastwide OFL was then apportioned to each management area based on the proportion of historical catches North and South of 40$^\circ$ 10' Latitude. DB-SRA does not assess overfished status, but assuming that current depletion was at the management target on average (e.g. 40%), the 2010 assessment found that `r spp` had a 52% chance of experiencing overfishing, in that recent coastwide catch of `r spp` slightly exceeded the median coastwide OFL estimate. 

The current OFL and ACLs for `r spp` North of 40$^\circ$ 10' Lat. N., the state/specific ACL allocation (58.4% for `r state`; Groundfish Management Team, pers. comm.), and the total removals are shown in Table \ref{tab:ofl}.
