### Data Weighting

Length composition data for the commercial fishery started with a sample size determined from the equation listed in Section \ref{commercial-fishery} (Table \ref{tab:com-len-samps}). The input sample size for the recreational fishery length composition data was set equal to the number of length samples by year (Table \ref{tab:len-samps}). 

The base  model was weighted using the Francis method, which was based on equation TA1.8 in Francis [-@francis_data_2011]. The weightings applied using the Francis method are provided in Table \ref{tab:dw}. This formulation looks at the mean length or age by year and the standard error of the mean to determine if, across years, the variability is adequately explained by the model. If the standard error of the mean does not encompass the model predictions, then that data source should be down-weighted. This method accounts for correlation in the data (i.e., the multinomial distribution). Sensitivities were performed examining the difference in weighting using McAllister-Ianelli Harmonic Mean Weighting [@mcallister_bayesian_1997] and the Dirichlet Multinomial Weighting [@thorson_model-based_2017].