### Modeling Platform and Structure

Stock Synthesis (SS) version 3.30.16 was used to estimate the parameters in the model. The R package r4ss, version 1.41.0, along with R version 4.0.2 were used to investigate and plot model fits. The NWFSC developed R packages nwfscSurvey_2.0 and PacFIN.Utilities_0.0.2.0000 were used for synthesis and processing of data for use in Stock Synthesis. 

### Priors

Priors were used with fixed parameter values for natural mortality and steepness in the base model.  The prior distribution for natural mortality was based on the Hamel [-@hamel_method_2015] meta-analytic approach with an assumed maximum age of `r model$accuage` years. The prior assumed a lognormal distribution for natural mortality with a median of `r model$parameters["NatM_p_1_Fem_GP_1","Value"]` and a standard deviation of 0.48. 

The prior for steepness assumed a beta distribution with mean of 0.72 and standard deviation of 0.158. The prior parameters are based on the Thorson-Dorn rockfish prior (commonly used in past West Coast rockfish assessments) conducted by James Thorson (personal communication, NWFSC, NOAA) which was reviewed and endorsed by the Scientific and Statistical Committee (SSC) in 2017. However, this approach was subsequently rejected for future analysis in 2019 when the new meta-analysis resulted in a mean value of approximately 0.95. In the absence of a new method for generating a prior for steepness the default approach reverts to the previously endorsed method, the 2017 value.

### Data Weighting

Length composition data for the comercial fishery started with a sample size determined from the equation listed in Section \ref{commercial-data}. The input sample size for the recreational fishery length composition data was set equal to the number of length samples by year.   

The base  model was weighted using the "Francis method", which was based on equation TA1.8 in Francis [-@francis_data_2011]. This formulation looks at the mean length or age and the variance of the mean to determine if across years, the variability is explained by the model. If the variability around the mean does not encompass the model predictions, then that data source should be down-weighted. This method accounts for correlation in the data (i.e., the multinomial distribution). Sensitivities were performed examining the difference in weighting using McAllister-Ianelli Harmonic Mean Weighting (McAllister et al. [-@mcallister_bayesian_1997]) and the Dirichlet Multinomial Weighting (Thorson et al. [-@thorson_model-based_2017]).